#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: install_atlas_core.sh [--env-name NAME] [--env-file PATH] [--optional] [--skip-env] [--no-configure] [--no-shim] [--verify-tools]

Create or update the core Atlas Python environment from environment.core.yml and
install the repository in editable mode. By default this also creates config.txt
and auto-detects legal/open tools from the active environment and PATH.
External licensed tools are not installed by this script.
EOF
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
env_name="${ATLAS_ENV_NAME:-docking-env}"
env_file="${ATLAS_ENV_FILE:-environment.core.yml}"
install_optional="${ATLAS_INSTALL_OPTIONAL:-0}"
skip_env="${ATLAS_SKIP_ENV_CREATE:-0}"
verify_tools="${ATLAS_VERIFY_TOOLS:-0}"
auto_config="${ATLAS_AUTO_CONFIG:-1}"
install_shim="${ATLAS_INSTALL_SHIM:-1}"
shim_dir="${ATLAS_SHIM_DIR:-}"
configure_args="${ATLAS_CONFIGURE_ARGS:-}"
env_manager=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-name)
      env_name="${2:?--env-name requires a value}"
      shift 2
      ;;
    --env-file)
      env_file="${2:?--env-file requires a value}"
      shift 2
      ;;
    --optional)
      install_optional="1"
      shift
      ;;
    --skip-env)
      skip_env="1"
      shift
      ;;
    --verify-tools)
      verify_tools="1"
      shift
      ;;
    --no-configure)
      auto_config="0"
      shift
      ;;
    --no-shim)
      install_shim="0"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

cd "$repo_root"

resolve_atlas_shim_dir() {
  if [[ -n "$shim_dir" ]]; then
    echo "$shim_dir"
    return 0
  fi

  local path_entry=""
  local env_bin="${CONDA_PREFIX:-}/bin"
  local -a path_entries=()
  IFS=':' read -r -a path_entries <<< "$PATH"
  for path_entry in "${path_entries[@]}"; do
    if [[ -z "$path_entry" || ! -d "$path_entry" || ! -w "$path_entry" ]]; then
      continue
    fi
    if [[ -n "${CONDA_PREFIX:-}" && "$path_entry" == "$env_bin" ]]; then
      continue
    fi
    case "$path_entry" in
      */envs/"$env_name"/bin|*/conda/envs/"$env_name"/bin|*/micromamba/envs/"$env_name"/bin)
        continue
        ;;
    esac
    echo "$path_entry"
    return 0
  done

  echo "$HOME/.local/bin"
}

install_atlas_shim() {
  local target_dir="$1"
  local env_name_for_shim="$2"
  local manager="$3"
  local shim_path="$target_dir/atlas"
  local env_bin="${CONDA_PREFIX:-}/bin"

  if [[ -n "${CONDA_PREFIX:-}" && "$target_dir" == "$env_bin" ]]; then
    echo "Atlas shim skipped: refusing to overwrite the real env CLI at $shim_path" >&2
    return 0
  fi
  if [[ -e "$shim_path" ]] && ! grep -q "Atlas environment shim" "$shim_path" 2>/dev/null; then
    echo "Atlas shim skipped: existing non-Atlas file at $shim_path" >&2
    echo "Set ATLAS_SHIM_DIR to another writable PATH directory, or move that file." >&2
    return 0
  fi

  mkdir -p "$target_dir"
  cat > "$shim_path" <<EOF
#!/usr/bin/env bash
# Atlas environment shim. Generated by tools/installers/install_atlas_core.sh.
set -euo pipefail

env_name="${env_name_for_shim}"
preferred_manager="${manager}"
atlas_entry='from cli.atlas_main_cli import main; raise SystemExit(main())'

if [[ -n "\${ATLAS_ENV_PREFIX:-}" && -x "\$ATLAS_ENV_PREFIX/bin/python" ]]; then
  exec "\$ATLAS_ENV_PREFIX/bin/python" -c "\$atlas_entry" "\$@"
fi

active_env_name="\${CONDA_DEFAULT_ENV:-}"
if [[ -z "\$active_env_name" && -n "\${CONDA_PREFIX:-}" ]]; then
  active_env_name="\$(basename "\$CONDA_PREFIX")"
fi

if [[ -n "\${CONDA_PREFIX:-}" && "\$active_env_name" == "\$env_name" && -x "\$CONDA_PREFIX/bin/python" ]]; then
  exec "\$CONDA_PREFIX/bin/python" -c "\$atlas_entry" "\$@"
fi

manager_exe=""
if [[ -n "\$preferred_manager" ]] && command -v "\$preferred_manager" >/dev/null 2>&1; then
  manager_exe="\$(command -v "\$preferred_manager")"
elif command -v micromamba >/dev/null 2>&1; then
  manager_exe="\$(command -v micromamba)"
  preferred_manager="micromamba"
elif command -v conda >/dev/null 2>&1; then
  manager_exe="\$(command -v conda)"
  preferred_manager="conda"
fi

if [[ -z "\$manager_exe" ]]; then
  echo "Atlas shim error: micromamba/conda is not available on PATH." >&2
  echo "Load your environment manager module, or set ATLAS_ENV_PREFIX to the env path." >&2
  exit 127
fi

exec "\$manager_exe" run -n "\$env_name" python -c "\$atlas_entry" "\$@"
EOF
  chmod +x "$shim_path"
  echo "Atlas environment shim installed: $shim_path"
  case ":$PATH:" in
    *":$target_dir:"*) ;;
    *)
      echo "Add this to PATH to call Atlas without activating the env:"
      echo "  export PATH=\"$target_dir:\$PATH\""
      ;;
  esac
}

if [[ "$skip_env" != "1" ]]; then
  if [[ ! -f "$env_file" ]]; then
    echo "Environment file not found: $env_file" >&2
    exit 2
  fi

  if command -v micromamba >/dev/null 2>&1; then
    env_manager="micromamba"
    if ! micromamba env list | awk '{print $1}' | grep -qx "$env_name"; then
      micromamba create -y -n "$env_name" -f "$env_file"
    else
      micromamba env update -n "$env_name" -f "$env_file"
    fi
    if [[ "$install_optional" == "1" ]]; then
      micromamba env update -n "$env_name" -f environment.optional.yml
    fi
    eval "$(micromamba shell hook --shell bash)"
    micromamba activate "$env_name"
  elif command -v conda >/dev/null 2>&1; then
    env_manager="conda"
    if ! conda env list | awk '{print $1}' | grep -qx "$env_name"; then
      conda env create -n "$env_name" -f "$env_file"
    else
      conda env update -n "$env_name" -f "$env_file"
    fi
    if [[ "$install_optional" == "1" ]]; then
      conda env update -n "$env_name" -f environment.optional.yml
    fi
    source "$(conda info --base)/etc/profile.d/conda.sh"
    conda activate "$env_name"
  else
    echo "Neither micromamba nor conda was found on PATH." >&2
    echo "Install one of them, or rerun with --skip-env inside an active Python environment." >&2
    exit 2
  fi
elif command -v micromamba >/dev/null 2>&1; then
  env_manager="micromamba"
elif command -v conda >/dev/null 2>&1; then
  env_manager="conda"
fi

python -m pip install -e .

if [[ "$install_shim" == "1" ]]; then
  shim_dir="$(resolve_atlas_shim_dir)"
  install_atlas_shim "$shim_dir" "$env_name" "$env_manager"
fi

if [[ ! -f config.txt ]]; then
  cp config.example.txt config.txt
  echo "Created local config.txt from config.example.txt"
fi

if [[ "$auto_config" == "1" ]]; then
  # Best-effort local path detection while the newly installed environment is active.
  # shellcheck disable=SC2086
  python tools/installers/configure_local_tools.py $configure_args
else
  echo "Config auto-detection skipped. Run atlas init later, or omit --no-configure."
fi

atlas --help >/dev/null
echo "Atlas CLI installed: $(command -v atlas)"

if [[ "$verify_tools" == "1" ]]; then
  atlas --verify-tools
else
  echo "External tool verification skipped. Run atlas --verify-tools after configuring local tool paths."
fi
