"""Auditable classification of declared and reconstructed final-score sources."""

from __future__ import annotations

import hashlib
import json
import math
import re
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from typing import Any, Mapping


FINAL_SCORE_SOURCE_CONTRACT_VERSION = "atlas_final_score_source_v1"
RECONSTRUCTED_PREFIX = "reconstructed:"
_ROW_SEMANTIC_FINGERPRINT_VERSION = "atlas_score_source_row_semantics_v1"

CONSENSUS_VS_DECOY_Z = "consensus_vs_decoy_z"
SCORCH_CNN_BLEND_VS_DECOY_Z = "scorch_cnn_percentile_blend_vs_decoy_z"
AVAILABLE_COMPONENT_BLEND_VS_DECOY_Z = (
    "available_component_scorch_cnn_percentile_blend_vs_decoy_z"
)
LEGACY_NEUTRAL_IMPUTED_BLEND_VS_DECOY_Z = (
    "legacy_neutral_imputed_scorch_cnn_percentile_blend_vs_decoy_z"
)
LEGACY_SCORCH_NEUTRAL_CNN_VS_DECOY_Z = (
    "legacy_scorch_percentile_neutral_cnn_placeholder_vs_decoy_z"
)
COMPARISON_CONSENSUS_VS_REFERENCE_DECOY_Z = (
    "comparison_run_consensus_vs_reference_decoy_z"
)

_SHA256 = re.compile(r"^[0-9a-f]{64}$")

# These definitions are intentionally narrow. Each accepted field is generated by
# documented Atlas code as a higher-is-better population-Z score. Raw consensus,
# raw SCORCH, rank percentiles, stage labels, and generic "decoy standardized"
# strings are not aliases for these sources.
_SOURCE_DEFINITIONS: dict[str, dict[str, Any]] = {
    CONSENSUS_VS_DECOY_Z: {
        "display_name": "Consensus versus same-run decoy Z",
        "family": "consensus_decoy_standardized",
        "normalization": "population_z_score_against_same_run_decoys",
        "formula": "z=(consensus_score-decoy_mean)/decoy_population_sd",
        "direction": "higher_is_better",
        "score_pose_linkage_requirement": "aggregate_no_unique_pose",
        "pose_lineage_semantics": (
            "Consensus combines docking-engine score signals; the normalized "
            "aggregate does not identify one pose."
        ),
        "selection_columns": [
            "z_vs_decoys_consensus",
            "t_vs_decoys_consensus",
        ],
        "implementation_reference": (
            "src.post_docking.rescoring.rescore_reranker:rerank_with_scorch"
        ),
    },
    SCORCH_CNN_BLEND_VS_DECOY_Z: {
        "display_name": "SCORCH/CNN percentile-blend family versus decoy Z",
        "family": "scorch_cnn_blend_decoy_standardized_unspecified_revision",
        "normalization": "population_z_score_against_same_run_decoys",
        "formula": "z=(documented_percentile_blend-decoy_mean)/decoy_population_sd",
        "direction": "higher_is_better",
        "score_pose_linkage_requirement": (
            "component_selected_poses_may_differ_no_unique_blend_pose"
        ),
        "pose_lineage_semantics": (
            "A bare z_vs_decoys_blend declaration identifies the normalized "
            "blend family but not its historical missing-component policy. It "
            "does not identify one pose. Reconstructed rows are assigned a "
            "more specific revision only when row evidence verifies it."
        ),
        "selection_columns": ["z_vs_decoys_blend", "t_vs_decoys_blend"],
        "implementation_reference": (
            "src.post_docking.rescoring.rescore_reranker:rerank_with_scorch"
        ),
    },
    AVAILABLE_COMPONENT_BLEND_VS_DECOY_Z: {
        "display_name": (
            "Available-component SCORCH/CNN percentile blend versus decoy Z"
        ),
        "family": "available_component_scorch_cnn_blend_decoy_standardized",
        "normalization": "population_z_score_against_same_run_decoys",
        "formula": (
            "z=(renormalized_available_component_percentile_blend-decoy_mean)"
            "/decoy_population_sd"
        ),
        "direction": "higher_is_better",
        "score_pose_linkage_requirement": (
            "component_selected_poses_may_differ_no_unique_blend_pose"
        ),
        "pose_lineage_semantics": (
            "The current blend can be SCORCH-only, CNN-only, or use both "
            "available components with weights renormalized over present "
            "components. SCORCH retains selected/rescored stage lineage but "
            "not an immutable pose identifier in this score contract; CNN is "
            "selected independently by cnn_score*cnn_affinity. A two-component "
            "blend can therefore combine distinct poses and is never assigned "
            "one pose."
        ),
        "selection_columns": ["z_vs_decoys_blend", "t_vs_decoys_blend"],
        "implementation_reference": (
            "src.post_docking.rescoring.rescore_reranker:_blend_available_percentiles"
        ),
    },
    LEGACY_NEUTRAL_IMPUTED_BLEND_VS_DECOY_Z: {
        "display_name": (
            "Legacy neutral-imputed SCORCH/CNN percentile blend versus decoy Z"
        ),
        "family": "legacy_neutral_imputed_scorch_cnn_blend_decoy_standardized",
        "normalization": "population_z_score_against_same_run_decoys",
        "formula": (
            "z=((0.65*scorch_percentile+0.35*cnn_percentile)-decoy_mean)"
            "/decoy_population_sd; a missing component percentile is 0.5"
        ),
        "direction": "higher_is_better",
        "score_pose_linkage_requirement": (
            "component_selected_poses_may_differ_no_unique_blend_pose"
        ),
        "pose_lineage_semantics": (
            "Legacy rows used a neutral 0.5 percentile placeholder for a "
            "missing component. When both components are observed, their "
            "selected poses may differ; no unique blend pose is assigned."
        ),
        "selection_columns": ["z_vs_decoys_blend", "t_vs_decoys_blend"],
        "implementation_reference": (
            "src.post_docking.rescoring.rescore_reranker historical pre-"
            "89efcf90797304d6b56b1813749ca4a5b599aa07 implementation"
        ),
    },
    LEGACY_SCORCH_NEUTRAL_CNN_VS_DECOY_Z: {
        "display_name": (
            "Legacy SCORCH percentile with neutral CNN placeholder versus decoy Z"
        ),
        "family": "legacy_scorch_decoy_standardized_neutral_cnn_placeholder",
        "normalization": "population_z_score_against_same_run_decoys",
        "formula": (
            "z=((0.65*scorch_percentile+0.35*0.5)-decoy_mean)/decoy_population_sd"
        ),
        "direction": "higher_is_better",
        "score_pose_linkage_requirement": (
            "scorch_rescored_stage_lineage_no_immutable_pose_identifier"
        ),
        "pose_lineage_semantics": (
            "CNN was not observed and its legacy percentile placeholder was "
            "0.5. The score therefore ranks SCORCH percentile evidence after "
            "a positive affine transform. A rescored stage may be recorded, "
            "but these historical rows do not contain an immutable pose ID; "
            "the score is never assigned to a pose."
        ),
        "selection_columns": ["z_vs_decoys_blend", "t_vs_decoys_blend"],
        "implementation_reference": (
            "src.post_docking.rescoring.rescore_reranker historical pre-"
            "89efcf90797304d6b56b1813749ca4a5b599aa07 implementation"
        ),
    },
    COMPARISON_CONSENSUS_VS_REFERENCE_DECOY_Z: {
        "display_name": "Consensus versus referenced-run decoy Z",
        "family": "comparison_consensus_decoy_standardized",
        "normalization": "population_z_score_against_referenced_run_decoys",
        "formula": "z=(consensus_score-reference_decoy_mean)/reference_decoy_population_sd",
        "direction": "higher_is_better",
        "score_pose_linkage_requirement": "aggregate_no_unique_pose",
        "pose_lineage_semantics": (
            "Consensus is aggregate score evidence and the referenced-run "
            "normalization does not create a unique pose association."
        ),
        "selection_columns": ["z_vs_compare_run_consensus"],
        "implementation_reference": (
            "analysis.ml.materialize_final_score:materialize_final_score"
        ),
    },
}

_DECLARED_ALIASES = {
    CONSENSUS_VS_DECOY_Z: CONSENSUS_VS_DECOY_Z,
    "z_vs_decoys_consensus": CONSENSUS_VS_DECOY_Z,
    "t_vs_decoys_consensus": CONSENSUS_VS_DECOY_Z,
    SCORCH_CNN_BLEND_VS_DECOY_Z: SCORCH_CNN_BLEND_VS_DECOY_Z,
    "z_vs_decoys_blend": SCORCH_CNN_BLEND_VS_DECOY_Z,
    "t_vs_decoys_blend": SCORCH_CNN_BLEND_VS_DECOY_Z,
    AVAILABLE_COMPONENT_BLEND_VS_DECOY_Z: AVAILABLE_COMPONENT_BLEND_VS_DECOY_Z,
    LEGACY_NEUTRAL_IMPUTED_BLEND_VS_DECOY_Z: (LEGACY_NEUTRAL_IMPUTED_BLEND_VS_DECOY_Z),
    LEGACY_SCORCH_NEUTRAL_CNN_VS_DECOY_Z: (LEGACY_SCORCH_NEUTRAL_CNN_VS_DECOY_Z),
    (
        COMPARISON_CONSENSUS_VS_REFERENCE_DECOY_Z
    ): COMPARISON_CONSENSUS_VS_REFERENCE_DECOY_Z,
    "z_vs_compare_run_consensus": COMPARISON_CONSENSUS_VS_REFERENCE_DECOY_Z,
    "comparison_run_consensus_fallback": (COMPARISON_CONSENSUS_VS_REFERENCE_DECOY_Z),
}

_COLUMN_GROUPS = {
    "consensus": (
        "z_vs_decoys_consensus",
        "t_vs_decoys_consensus",
    ),
    "blend": ("z_vs_decoys_blend", "t_vs_decoys_blend"),
    "comparison_consensus": ("z_vs_compare_run_consensus",),
}
_BLEND_REVISION_SOURCES = frozenset(
    {
        AVAILABLE_COMPONENT_BLEND_VS_DECOY_Z,
        LEGACY_NEUTRAL_IMPUTED_BLEND_VS_DECOY_Z,
        LEGACY_SCORCH_NEUTRAL_CNN_VS_DECOY_Z,
    }
)

_CONTRACT_PAYLOAD = {
    "contract_version": FINAL_SCORE_SOURCE_CONTRACT_VERSION,
    "definitions": _SOURCE_DEFINITIONS,
    "declared_aliases": _DECLARED_ALIASES,
    "reconstruction_policy": {
        "declared_source_is_never_overwritten": True,
        "requires_unique_named_normalized_source": True,
        "z_and_t_legacy_aliases_may_co_match_one_source": True,
        "blend_revision_requires_row_semantic_fingerprint": True,
        "requires_exact_decimal_value_equality": True,
        "requires_immutable_file_and_row_provenance": True,
        "reconstruction_evidence_binds_exact_canonical_source": True,
        "declared_source_requires_matching_normalized_column": True,
        "row_semantic_fingerprint_version": _ROW_SEMANTIC_FINGERPRINT_VERSION,
        "ambiguous_matches_fail_closed": True,
        "raw_or_generic_sources_fail_closed": True,
    },
}
FINAL_SCORE_SOURCE_CONTRACT_SHA256 = hashlib.sha256(
    json.dumps(_CONTRACT_PAYLOAD, sort_keys=True, separators=(",", ":")).encode("utf-8")
).hexdigest()


@dataclass(frozen=True)
class ScoreSourceClassification:
    """One score-source classification projected into release outputs."""

    declared_source: str | None
    reconstructed_source: str | None
    effective_source: str | None
    canonical_source: str | None
    family: str | None
    pose_linkage_requirement: str | None
    classification: str
    eligible: bool
    reason: str


def _text(value: Any) -> str:
    return "" if value is None else str(value).strip()


def _decimal(value: Any) -> Decimal | None:
    token = _text(value)
    if not token:
        return None
    try:
        parsed = Decimal(token)
    except (InvalidOperation, ValueError):
        return None
    return parsed if parsed.is_finite() else None


def _canonical_decimal_text(value: Decimal) -> str:
    if value == 0:
        return "0"
    return format(value.normalize(), "f")


def _finite_float(value: Any) -> float | None:
    parsed = _decimal(value)
    return float(parsed) if parsed is not None else None


def _approximately_serialized(observed: float, expected: float) -> bool:
    """Allow only the error expected from historical six-significant-digit CSVs."""
    return math.isclose(observed, expected, rel_tol=3e-5, abs_tol=3e-6)


def _blend_z_formula_is_verified(row: Mapping[str, Any]) -> bool:
    blend = _finite_float(row.get("ml_blend_score"))
    mu = _finite_float(row.get("blend_mu_decoy"))
    sigma = _finite_float(row.get("blend_sigma_decoy"))
    z_score = _finite_float(
        row.get("z_vs_decoys_blend") or row.get("t_vs_decoys_blend")
    )
    n_decoys = _finite_float(row.get("blend_n_decoys"))
    if None in {blend, mu, sigma, z_score, n_decoys}:
        return False
    assert blend is not None and mu is not None and sigma is not None
    assert z_score is not None and n_decoys is not None
    return (
        sigma > 0
        and n_decoys >= 1
        and _approximately_serialized(z_score, (blend - mu) / sigma)
    )


def _current_blend_semantics_are_verified(row: Mapping[str, Any]) -> bool:
    mode = _text(row.get("ml_blend_mode")).lower()
    if mode not in {"scorch_only", "cnn_only", "scorch_cnn"}:
        return False
    scorch_pct = _finite_float(row.get("scorch_pct"))
    cnn_pct = _finite_float(row.get("cnn_pct"))
    blend = _finite_float(row.get("ml_blend_score"))
    scorch_weight = _finite_float(row.get("ml_blend_scorch_weight_effective"))
    cnn_weight = _finite_float(row.get("ml_blend_cnn_weight_effective"))
    if None in {blend, scorch_weight, cnn_weight}:
        return False
    assert blend is not None and scorch_weight is not None and cnn_weight is not None
    expected_components = {
        "scorch_only": (True, False),
        "cnn_only": (False, True),
        "scorch_cnn": (True, True),
    }[mode]
    if (scorch_pct is not None, cnn_pct is not None) != expected_components:
        return False
    if not _approximately_serialized(scorch_weight + cnn_weight, 1.0):
        return False
    expected = (scorch_pct or 0.0) * scorch_weight + (cnn_pct or 0.0) * cnn_weight
    return _approximately_serialized(blend, expected) and _blend_z_formula_is_verified(
        row
    )


def _legacy_blend_semantics(row: Mapping[str, Any]) -> str | None:
    if (
        _text(row.get("ml_blend_mode"))
        or _text(row.get("ml_blend_scorch_weight_effective"))
        or _text(row.get("ml_blend_cnn_weight_effective"))
    ):
        return None
    scorch_pct = _finite_float(row.get("scorch_pct"))
    cnn_pct = _finite_float(row.get("cnn_pct"))
    blend = _finite_float(row.get("ml_blend_score"))
    if None in {scorch_pct, cnn_pct, blend}:
        return None
    assert scorch_pct is not None and cnn_pct is not None and blend is not None
    expected = 0.65 * scorch_pct + 0.35 * cnn_pct
    if not _approximately_serialized(blend, expected):
        return None
    if not _blend_z_formula_is_verified(row):
        return None

    cnn_observed = any(
        _text(row.get(column))
        for column in ("cnn_vs_used", "cnn_score_used", "cnn_affinity_used")
    )
    scorch_observed = any(
        _text(row.get(column)) for column in ("scorch_composite", "SCORCH_score_used")
    )
    if scorch_observed and not cnn_observed and _approximately_serialized(cnn_pct, 0.5):
        return LEGACY_SCORCH_NEUTRAL_CNN_VS_DECOY_Z
    if scorch_observed or cnn_observed:
        return LEGACY_NEUTRAL_IMPUTED_BLEND_VS_DECOY_Z
    return None


def _source_for_group(group: str, row: Mapping[str, Any]) -> str | None:
    if group == "consensus":
        return CONSENSUS_VS_DECOY_Z
    if group == "comparison_consensus":
        return COMPARISON_CONSENSUS_VS_REFERENCE_DECOY_Z
    if group == "blend":
        if _current_blend_semantics_are_verified(row):
            return AVAILABLE_COMPONENT_BLEND_VS_DECOY_Z
        return _legacy_blend_semantics(row)
    return None


def _matching_columns_for_source(
    row: Mapping[str, Any], canonical: str, final_score: Decimal
) -> list[str]:
    return [
        str(column)
        for column in _SOURCE_DEFINITIONS[canonical]["selection_columns"]
        if _decimal(row.get(str(column))) == final_score
    ]


def _row_semantic_fingerprint(
    *,
    canonical_source: str,
    final_score: Decimal,
    matched_columns: list[str],
    result_sha256: str,
) -> str:
    payload = {
        "canonical_source": canonical_source,
        "contract_sha256": FINAL_SCORE_SOURCE_CONTRACT_SHA256,
        "final_score": _canonical_decimal_text(final_score),
        "matched_columns": matched_columns,
        "result_sha256": _text(result_sha256).lower(),
        "version": _ROW_SEMANTIC_FINGERPRINT_VERSION,
    }
    return hashlib.sha256(_json(payload).encode("utf-8")).hexdigest()


def _blend_revision_matches_row(canonical: str, row: Mapping[str, Any]) -> bool:
    return (
        canonical not in _BLEND_REVISION_SOURCES
        or _source_for_group("blend", row) == canonical
    )


def _json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)


def score_source_browser_contract() -> dict[str, Any]:
    """Return the public, provider-neutral score-source contract."""
    return {
        **_CONTRACT_PAYLOAD,
        "contract_sha256": FINAL_SCORE_SOURCE_CONTRACT_SHA256,
        "eligible_canonical_sources": sorted(_SOURCE_DEFINITIONS),
        "reconstructed_prefix": RECONSTRUCTED_PREFIX,
    }


def classify_declared_source(value: Any) -> tuple[str | None, str | None]:
    """Return the canonical source and family for a controlled declaration."""
    canonical = _DECLARED_ALIASES.get(_text(value).lower())
    if canonical is None:
        return None, None
    return canonical, str(_SOURCE_DEFINITIONS[canonical]["family"])


def score_source_pose_linkage_requirement(value: Any) -> str | None:
    """Return the versioned pose-linkage requirement for a controlled source."""
    token = _text(value).lower()
    for prefix in ("declared:", RECONSTRUCTED_PREFIX):
        if token.startswith(prefix):
            token = token.removeprefix(prefix)
            break
    canonical, _ = classify_declared_source(token)
    if canonical is None:
        return None
    return str(_SOURCE_DEFINITIONS[canonical]["score_pose_linkage_requirement"])


def build_score_source_materialization(
    row: Mapping[str, Any],
    *,
    input_csv_sha256: str,
    source_row_number: int,
    result_sha256: str,
) -> tuple[str | None, str, str | None]:
    """Build additive reconstruction fields without changing a declared source.

    Exact equality is only one part of the evidence: candidate columns have fixed,
    versioned Atlas semantics and the evidence binds the decision to an immutable
    input file, logical row number, and canonical raw-row hash.
    """
    final_score = _decimal(row.get("final_score"))
    if final_score is None:
        return None, "missing_final_score", None

    declared = _text(row.get("final_score_source"))
    declared_canonical, _ = classify_declared_source(declared)
    if declared:
        declared_matches = (
            _matching_columns_for_source(row, declared_canonical, final_score)
            if declared_canonical
            else []
        )
        if declared_canonical is None:
            status = "declared_unclassified"
            reason = "declared_source_not_in_controlled_normalized_vocabulary"
        elif not declared_matches:
            status = "declared_value_mismatch"
            reason = "declared_source_does_not_match_an_allowed_normalized_column"
        elif not _blend_revision_matches_row(declared_canonical, row):
            status = "declared_semantics_unverified"
            reason = "declared_blend_revision_row_semantics_fail_closed"
        else:
            status = "declared_classified"
            reason = (
                "controlled_declared_normalized_source_exact_value_and_revision_match"
                if declared_canonical in _BLEND_REVISION_SOURCES
                else "controlled_declared_normalized_source_exact_value_match"
            )
        evidence = _evidence(
            status=status,
            reason=reason,
            input_csv_sha256=input_csv_sha256,
            source_row_number=source_row_number,
            result_sha256=result_sha256,
            matched_columns=declared_matches,
            final_score=final_score,
            canonical_source=declared_canonical,
            bind_row_semantics=(
                status == "declared_classified"
                and declared_canonical in _BLEND_REVISION_SOURCES
            ),
        )
        return None, status, _json(evidence)

    matched_by_group = {
        group: [
            column for column in columns if _decimal(row.get(column)) == final_score
        ]
        for group, columns in _COLUMN_GROUPS.items()
    }
    matched_by_group = {
        group: columns for group, columns in matched_by_group.items() if columns
    }
    matched_columns = [
        column for group in _COLUMN_GROUPS for column in matched_by_group.get(group, [])
    ]

    if len(matched_by_group) == 1:
        group = next(iter(matched_by_group))
        canonical = _source_for_group(group, row)
    else:
        canonical = None

    if canonical is not None:
        reconstructed = f"{RECONSTRUCTED_PREFIX}{canonical}"
        status = "reconstructed_verified"
        reason = (
            "unique_documented_normalized_source_exact_value_match_with_legacy_alias"
            if len(matched_columns) > 1
            else "unique_documented_normalized_source_exact_value_match"
        )
    elif len(matched_by_group) > 1:
        reconstructed = None
        status = "reconstruction_ambiguous"
        reason = "multiple_documented_normalized_sources_exactly_match"
    elif matched_by_group:
        reconstructed = None
        status = "reconstruction_unclassified"
        reason = "normalized_blend_column_matches_but_revision_semantics_fail_closed"
    else:
        reconstructed = None
        status = "reconstruction_unclassified"
        reason = "no_documented_normalized_source_exactly_matches"

    evidence = _evidence(
        status=status,
        reason=reason,
        input_csv_sha256=input_csv_sha256,
        source_row_number=source_row_number,
        result_sha256=result_sha256,
        matched_columns=matched_columns,
        final_score=final_score,
        canonical_source=canonical,
        bind_row_semantics=status == "reconstructed_verified",
    )
    return reconstructed, status, _json(evidence)


def _evidence(
    *,
    status: str,
    reason: str,
    input_csv_sha256: str,
    source_row_number: int,
    result_sha256: str,
    matched_columns: list[str],
    final_score: Decimal,
    canonical_source: str | None,
    bind_row_semantics: bool,
) -> dict[str, Any]:
    evidence = {
        "contract_version": FINAL_SCORE_SOURCE_CONTRACT_VERSION,
        "contract_sha256": FINAL_SCORE_SOURCE_CONTRACT_SHA256,
        "status": status,
        "reason": reason,
        "input_csv_sha256": input_csv_sha256,
        "source_row_number": source_row_number,
        "result_sha256": result_sha256,
        "matched_columns": matched_columns,
        "final_score": _canonical_decimal_text(final_score),
        "canonical_source": canonical_source,
        "ambiguity_state": (
            "multiple"
            if status == "reconstruction_ambiguous"
            else "unique"
            if status == "reconstructed_verified"
            else "not_applicable"
        ),
    }
    if bind_row_semantics:
        assert canonical_source is not None
        evidence["row_semantic_fingerprint_version"] = _ROW_SEMANTIC_FINGERPRINT_VERSION
        evidence["row_semantic_fingerprint_sha256"] = _row_semantic_fingerprint(
            canonical_source=canonical_source,
            final_score=final_score,
            matched_columns=matched_columns,
            result_sha256=result_sha256,
        )
    return evidence


def classify_materialized_source(row: Mapping[str, Any]) -> ScoreSourceClassification:
    """Validate materialized source fields and return fail-closed eligibility."""
    final_score = _decimal(row.get("final_score"))
    if final_score is None:
        return ScoreSourceClassification(
            None,
            None,
            None,
            None,
            None,
            None,
            "missing_final_score",
            False,
            "final score is missing",
        )

    declared = _text(row.get("final_score_source")) or None
    canonical, family = classify_declared_source(declared)
    if declared:
        if canonical:
            stored_status = _text(row.get("final_score_source_classification"))
            evidence = _parse_evidence(row.get("final_score_source_evidence_json"))
            reason = _validate_declared_evidence(
                canonical=canonical,
                stored_status=stored_status,
                evidence=evidence,
                final_score=final_score,
                input_csv_sha256=row.get("selected_result_input_csv_sha256"),
                source_row_number=row.get("selected_result_source_row_number"),
                result_sha256=row.get("selected_result_sha256"),
            )
            if reason is not None:
                return ScoreSourceClassification(
                    declared,
                    None,
                    None,
                    None,
                    None,
                    None,
                    (
                        "declared_evidence_invalid"
                        if stored_status == "declared_classified"
                        else stored_status or "declared_unclassified"
                    ),
                    False,
                    reason,
                )
            return ScoreSourceClassification(
                declared,
                None,
                f"declared:{canonical}",
                canonical,
                family,
                str(_SOURCE_DEFINITIONS[canonical]["score_pose_linkage_requirement"]),
                "declared_classified",
                True,
                "verified controlled declaration and immutable row evidence",
            )
        return ScoreSourceClassification(
            declared,
            None,
            None,
            None,
            None,
            None,
            "declared_unclassified",
            False,
            "declared source is not a controlled normalized source",
        )

    reconstructed = _text(row.get("final_score_source_reconstructed")) or None
    stored_status = _text(row.get("final_score_source_classification"))
    evidence = _parse_evidence(row.get("final_score_source_evidence_json"))
    reason = _validate_reconstruction_evidence(
        reconstructed=reconstructed,
        stored_status=stored_status,
        evidence=evidence,
        final_score=final_score,
        input_csv_sha256=row.get("selected_result_input_csv_sha256"),
        source_row_number=row.get("selected_result_source_row_number"),
        result_sha256=row.get("selected_result_sha256"),
    )
    if reason is not None:
        return ScoreSourceClassification(
            None,
            reconstructed,
            None,
            None,
            None,
            None,
            (
                "reconstruction_evidence_invalid"
                if stored_status == "reconstructed_verified"
                else stored_status or "reconstruction_unclassified"
            ),
            False,
            reason,
        )

    assert reconstructed is not None
    canonical = reconstructed.removeprefix(RECONSTRUCTED_PREFIX)
    return ScoreSourceClassification(
        None,
        reconstructed,
        reconstructed,
        canonical,
        str(_SOURCE_DEFINITIONS[canonical]["family"]),
        str(_SOURCE_DEFINITIONS[canonical]["score_pose_linkage_requirement"]),
        "reconstructed_verified",
        True,
        "verified immutable reconstruction evidence",
    )


def _parse_evidence(value: Any) -> Mapping[str, Any] | None:
    if isinstance(value, Mapping):
        return value
    try:
        payload = json.loads(_text(value))
    except (TypeError, ValueError):
        return None
    return payload if isinstance(payload, Mapping) else None


def _validate_bound_evidence(
    *,
    canonical: str,
    expected_status: str,
    evidence: Mapping[str, Any] | None,
    final_score: Decimal,
    input_csv_sha256: Any,
    source_row_number: Any,
    result_sha256: Any,
    require_row_semantic_fingerprint: bool,
) -> str | None:
    if evidence is None:
        return "score-source evidence is missing or malformed"
    if evidence.get("contract_version") != FINAL_SCORE_SOURCE_CONTRACT_VERSION:
        return "score-source contract version does not match"
    if evidence.get("contract_sha256") != FINAL_SCORE_SOURCE_CONTRACT_SHA256:
        return "score-source contract hash does not match"
    if evidence.get("status") != expected_status:
        return "score-source evidence status does not match"
    if evidence.get("canonical_source") != canonical:
        return "score-source evidence does not bind the exact canonical source"
    if _decimal(evidence.get("final_score")) != final_score:
        return "score-source evidence final score does not match materialized score"

    raw_columns = evidence.get("matched_columns")
    if (
        not isinstance(raw_columns, list)
        or not raw_columns
        or not all(isinstance(column, str) for column in raw_columns)
    ):
        return "score-source evidence does not identify normalized source columns"
    columns = [str(column) for column in raw_columns]
    if len(columns) != len(set(columns)):
        return "score-source evidence repeats normalized source columns"
    allowed_columns = {
        str(column) for column in _SOURCE_DEFINITIONS[canonical]["selection_columns"]
    }
    if any(column not in allowed_columns for column in columns):
        return "score-source evidence columns are not allowed for the canonical source"

    expected_file_hash = _text(input_csv_sha256).lower()
    expected_row_hash = _text(result_sha256).lower()
    try:
        expected_row_number = int(source_row_number)
    except (TypeError, ValueError):
        return "selected result row provenance is incomplete"
    if not _SHA256.fullmatch(expected_file_hash) or not _SHA256.fullmatch(
        expected_row_hash
    ):
        return "selected result hashes are incomplete"
    if expected_row_number < 2:
        return "selected result row number is invalid"
    if _text(evidence.get("input_csv_sha256")).lower() != expected_file_hash:
        return "score-source input file hash does not match selected result"
    if _text(evidence.get("result_sha256")).lower() != expected_row_hash:
        return "score-source row hash does not match selected result"
    evidence_row_number_raw = evidence.get("source_row_number")
    if evidence_row_number_raw is None:
        return "score-source row number is malformed"
    try:
        evidence_row_number = int(evidence_row_number_raw)
    except (TypeError, ValueError):
        return "score-source row number is malformed"
    if evidence_row_number != expected_row_number:
        return "score-source row number does not match selected result"

    if not require_row_semantic_fingerprint:
        return None
    if (
        evidence.get("row_semantic_fingerprint_version")
        != _ROW_SEMANTIC_FINGERPRINT_VERSION
    ):
        return "row semantic fingerprint version does not match"
    observed_fingerprint = _text(
        evidence.get("row_semantic_fingerprint_sha256")
    ).lower()
    if not _SHA256.fullmatch(observed_fingerprint):
        return "row semantic fingerprint is missing or malformed"
    expected_fingerprint = _row_semantic_fingerprint(
        canonical_source=canonical,
        final_score=final_score,
        matched_columns=columns,
        result_sha256=expected_row_hash,
    )
    if observed_fingerprint != expected_fingerprint:
        return "row semantic fingerprint does not verify the exact source revision"
    return None


def _validate_declared_evidence(
    *,
    canonical: str,
    stored_status: str,
    evidence: Mapping[str, Any] | None,
    final_score: Decimal,
    input_csv_sha256: Any,
    source_row_number: Any,
    result_sha256: Any,
) -> str | None:
    if stored_status != "declared_classified":
        return "controlled declared source lacks a verified exact-value classification"
    return _validate_bound_evidence(
        canonical=canonical,
        expected_status="declared_classified",
        evidence=evidence,
        final_score=final_score,
        input_csv_sha256=input_csv_sha256,
        source_row_number=source_row_number,
        result_sha256=result_sha256,
        require_row_semantic_fingerprint=canonical in _BLEND_REVISION_SOURCES,
    )


def _validate_reconstruction_evidence(
    *,
    reconstructed: str | None,
    stored_status: str,
    evidence: Mapping[str, Any] | None,
    final_score: Decimal,
    input_csv_sha256: Any,
    source_row_number: Any,
    result_sha256: Any,
) -> str | None:
    if reconstructed is None or stored_status != "reconstructed_verified":
        return "score lacks a unique verified reconstruction"
    if not reconstructed.startswith(RECONSTRUCTED_PREFIX):
        return "reconstructed source lacks the controlled prefix"
    canonical = reconstructed.removeprefix(RECONSTRUCTED_PREFIX)
    if canonical not in _SOURCE_DEFINITIONS:
        return "reconstructed source is not in the controlled vocabulary"
    reason = _validate_bound_evidence(
        canonical=canonical,
        expected_status="reconstructed_verified",
        evidence=evidence,
        final_score=final_score,
        input_csv_sha256=input_csv_sha256,
        source_row_number=source_row_number,
        result_sha256=result_sha256,
        require_row_semantic_fingerprint=True,
    )
    if reason is not None:
        return reason
    assert evidence is not None
    if evidence.get("ambiguity_state") != "unique":
        return "reconstruction evidence is ambiguous"
    return None


__all__ = [
    "AVAILABLE_COMPONENT_BLEND_VS_DECOY_Z",
    "COMPARISON_CONSENSUS_VS_REFERENCE_DECOY_Z",
    "CONSENSUS_VS_DECOY_Z",
    "FINAL_SCORE_SOURCE_CONTRACT_SHA256",
    "FINAL_SCORE_SOURCE_CONTRACT_VERSION",
    "LEGACY_NEUTRAL_IMPUTED_BLEND_VS_DECOY_Z",
    "LEGACY_SCORCH_NEUTRAL_CNN_VS_DECOY_Z",
    "RECONSTRUCTED_PREFIX",
    "SCORCH_CNN_BLEND_VS_DECOY_Z",
    "ScoreSourceClassification",
    "build_score_source_materialization",
    "classify_declared_source",
    "classify_materialized_source",
    "score_source_browser_contract",
    "score_source_pose_linkage_requirement",
]
