"""Backward-compatible facade for the split cli.qol package."""

from __future__ import annotations

import subprocess

from cli.postrun_hooks_support import _repo_root
from cli.qol.constants import (
    DEMO_RUN_ID,
    DEMO_ROWS,
    SLURM_BENCH2_CANARY_ARRAY,
    SLURM_BENCH2_CANARY_CPUS_PER_TASK,
    SLURM_BENCH2_CANARY_JOB_NAME,
    SLURM_BENCH2_CANARY_MAIN_ARGS,
    SLURM_BENCH2_CANARY_SCRIPT,
    SLURM_BENCH2_CANARY_TIME,
    SLURM_SUBMIT_DEFAULT_ARRAY,
    SLURM_SUBMIT_DEFAULT_CPUS_PER_TASK,
    SLURM_SUBMIT_DEFAULT_JOB_NAME,
    SLURM_SUBMIT_DEFAULT_SCRIPT,
)
from cli.qol.dispatch import dispatch
from cli.qol.ligands import (
    _cmd_library_alias,
    _cmd_ligands,
    _forwarded_pipeline_args,
    _print_ligand_paths,
    _print_ligand_sources,
    _run_with_library,
)
from cli.qol.manifest_repair import _cmd_repair_manifest, repair_run_manifest
from cli.qol.maintenance import (
    _cmd_artifacts,
    _cmd_debug,
    _cmd_dev,
    _cmd_reproduce,
    _cmd_screenshot,
    _cmd_throughput,
)
from cli.qol.ml import _cmd_ml
from cli.qol.new_run import (
    _cmd_first_run,
    _cmd_new_run,
    _first_run_plan_dir,
    _first_run_plan_manifest_out,
    _first_run_plan_selected_out,
)
from cli.qol.onboarding import (
    _all_required_ok,
    _build_setup_report,
    _check_imports,
    _cmd_demo,
    _cmd_help,
    _cmd_init,
    _cmd_setup_report,
    _cmd_smoke,
    _import_fix,
    _offline_demo_pathways,
    _offline_demo_uniprots,
    _print_setup_report,
    _setup_next_steps,
    _tool_fix,
    _write_example_input_docs,
)
from cli.qol.pipeline import _cmd_run
from cli.qol.reporting import _cmd_analysis, _cmd_report, _run_master_export
from cli.qol.run_panel import (
    _build_run_panel_parser,
    _cmd_run_panel,
    _pipeline_has_pdb_selection,
    _run_panel_install_ligands,
    _run_panel_install_targets,
    _run_panel_pipeline_args,
)
from cli.qol.slurm import (
    _apply_slurm_submit_presets,
    _cmd_slurm,
    _cmd_slurm_finalize,
    _cmd_slurm_submit,
    _extract_sbatch_job_id,
    _main_args_are_benchmark,
    _slurm_cpus_per_task_value,
)
from cli.qol.status import (
    _build_status,
    _cmd_runs,
    _cmd_status,
    _latest_run_id,
    _print_status,
    _read_manifest,
    _status_next_steps,
)
from cli.qol.targets import (
    _add_target_query_filter_args,
    _build_targets_parser,
    _cmd_targets,
    _cmd_targets_from_genes,
    _cmd_targets_genes,
    _cmd_targets_guide,
    _cmd_targets_install,
    _cmd_targets_search,
    _explain_target_csv,
    _print_target_install_result,
    _print_target_panels,
    _print_target_species,
)
from cli.qol.utils import _display_path, load_effective_config

__all__ = [
    "DEMO_RUN_ID",
    "DEMO_ROWS",
    "SLURM_BENCH2_CANARY_ARRAY",
    "SLURM_BENCH2_CANARY_CPUS_PER_TASK",
    "SLURM_BENCH2_CANARY_JOB_NAME",
    "SLURM_BENCH2_CANARY_MAIN_ARGS",
    "SLURM_BENCH2_CANARY_SCRIPT",
    "SLURM_BENCH2_CANARY_TIME",
    "SLURM_SUBMIT_DEFAULT_ARRAY",
    "SLURM_SUBMIT_DEFAULT_CPUS_PER_TASK",
    "SLURM_SUBMIT_DEFAULT_JOB_NAME",
    "SLURM_SUBMIT_DEFAULT_SCRIPT",
    "_add_target_query_filter_args",
    "_all_required_ok",
    "_apply_slurm_submit_presets",
    "_build_run_panel_parser",
    "_build_setup_report",
    "_build_status",
    "_build_targets_parser",
    "_check_imports",
    "_cmd_analysis",
    "_cmd_artifacts",
    "_cmd_debug",
    "_cmd_demo",
    "_cmd_dev",
    "_cmd_first_run",
    "_cmd_help",
    "_cmd_init",
    "_cmd_library_alias",
    "_cmd_ligands",
    "_cmd_ml",
    "_cmd_new_run",
    "_cmd_report",
    "_cmd_repair_manifest",
    "_cmd_reproduce",
    "_cmd_run",
    "_cmd_run_panel",
    "_cmd_runs",
    "_cmd_screenshot",
    "_cmd_setup_report",
    "_cmd_slurm",
    "_cmd_slurm_finalize",
    "_cmd_slurm_submit",
    "_cmd_smoke",
    "_cmd_status",
    "_cmd_targets",
    "_cmd_targets_from_genes",
    "_cmd_targets_genes",
    "_cmd_targets_guide",
    "_cmd_targets_install",
    "_cmd_targets_search",
    "_cmd_throughput",
    "_display_path",
    "_explain_target_csv",
    "_extract_sbatch_job_id",
    "_first_run_plan_dir",
    "_first_run_plan_manifest_out",
    "_first_run_plan_selected_out",
    "_forwarded_pipeline_args",
    "_import_fix",
    "_latest_run_id",
    "_main_args_are_benchmark",
    "_offline_demo_pathways",
    "_offline_demo_uniprots",
    "_pipeline_has_pdb_selection",
    "_print_ligand_paths",
    "_print_ligand_sources",
    "_print_setup_report",
    "_print_status",
    "_print_target_install_result",
    "_print_target_panels",
    "_print_target_species",
    "_read_manifest",
    "_repo_root",
    "_run_master_export",
    "_run_panel_install_ligands",
    "_run_panel_install_targets",
    "_run_panel_pipeline_args",
    "_run_with_library",
    "repair_run_manifest",
    "_setup_next_steps",
    "_slurm_cpus_per_task_value",
    "_status_next_steps",
    "_tool_fix",
    "_write_example_input_docs",
    "dispatch",
    "load_effective_config",
    "subprocess",
]
