from __future__ import annotations


def build_clustergrammer_client_script_runtime(
*,
container_id: str,
host_id: str,
viz_json_id: str,
meta_json_id: str,
rowmeta_json_id: str,
colmeta_json_id: str,
analysis_json_id: str,
scale_json_id: str,
scale_mode_label_id: str,
scale_breaks_label_id: str,
scale_fixed_label_id: str,
view_summary_id: str,
threshold_range_id: str,
threshold_value_id: str,
threshold_pct_id: str,
threshold_fdr_id: str,
threshold_scorch_fdr_id: str,
threshold_scorch_relaxed_fdr_id: str,
reset_button_id: str,
org_none_id: str,
org_safety_id: str,
org_adme_id: str,
org_family_id: str,
org_pathway_id: str,
safety_panel_id: str,
adme_panel_id: str,
safety_search_input_id: str,
safety_search_clear_id: str,
org_strip_id: str,
scale_legend_bar_id: str,
scale_legend_min_id: str,
scale_legend_mid_id: str,
scale_legend_mid2_id: str,
scale_legend_max_id: str,
scale_toggle_fixed_id: str,
scale_toggle_quantile_id: str,
safe_run_id: str,
ligand_prefix_json: str,
color_range_json: str,
row_order_js: str,
report_extras,
ligand_extras,
use_dendrogram: bool,
) -> str:
    return (
        "      if (colLabelObserver && typeof colLabelObserver.disconnect === \"function\") colLabelObserver.disconnect();\n"
        "      colLabelObserver = null;\n"
        "      if (typeof MutationObserver !== \"function\") return;\n"
        "      var target = container;\n"
        "      if (!target) return;\n"
        "      colLabelObserver = new MutationObserver(function() { scheduleColLabelSync(); });\n"
        "      colLabelObserver.observe(target, { childList: true, subtree: true, characterData: true });\n"
        "      scheduleColLabelSync();\n"
        "    }\n"
        "    function attachColLabelHandlers() {\n"
        "      var labels = colLabelNodes();\n"
        "      for (var i = 0; i < labels.length; i++) {\n"
        "        var label = labels[i];\n"
        "        if (label.getAttribute(\"data-cg-col-bound\") === \"1\") continue;\n"
        "        label.setAttribute(\"data-cg-col-bound\", \"1\");\n"
        "        label.setAttribute(\"tabindex\", \"0\");\n"
        "        label.setAttribute(\"role\", \"button\");\n"
        "        label.setAttribute(\"aria-label\", \"Select PDB target \" + String(rawColLabel(label) || \"\"));\n"
        "        label.addEventListener(\"pointerenter\", function(evt) {\n"
        "          var meta = lookupColLabelMeta(rawColLabel(this));\n"
        "          var lines = [\"pdb: \" + String(meta.pdb || \"\"), \"target_name: \" + String(meta.target_name || \"\")];\n"
        "          if (meta.variant_ph) lines.push(\"variant/pH: \" + String(meta.variant_ph));\n"
        "          if (meta.protein_family) lines.push(\"protein_family: \" + String(meta.protein_family));\n"
        "          appendTargetSafetyLines(lines, meta);\n"
        "          appendPromiscuityLines(lines, meta);\n"
        "          showHoverTip(lines, evt.clientX, evt.clientY);\n"
        "        });\n"
        "        label.addEventListener(\"pointermove\", function(evt) { moveHoverTip(evt.clientX, evt.clientY); });\n"
        "        label.addEventListener(\"pointerleave\", function() { hideHoverTip(); });\n"
        "      }\n"
        "    }\n"
        "    function attachRowLabelHandlers() {\n"
        "      var labels = rowLabelGroups();\n"
        "      for (var i = 0; i < labels.length; i++) {\n"
        "        var label = labels[i];\n"
        "        if (label.getAttribute(\"data-cg-row-bound\") === \"1\") continue;\n"
        "        label.setAttribute(\"data-cg-row-bound\", \"1\");\n"
        "        label.setAttribute(\"tabindex\", \"0\");\n"
        "        label.setAttribute(\"role\", \"button\");\n"
        "        label.setAttribute(\"aria-label\", \"Sort by ligand \" + String(rawRowGroupLabel(label) || \"\"));\n"
        "        label.addEventListener(\"pointerenter\", function(evt) {\n"
        "          var rowName = rawRowGroupLabel(this);\n"
        "          var meta = lookupRowLabelMeta(rowName);\n"
        "          var lines = [\"ligand: \" + rowName];\n"
        "          appendLigandAnnotationLines(lines, meta);\n"
        "          appendPromiscuityLines(lines, meta);\n"
        "          showHoverTip(lines, evt.clientX, evt.clientY);\n"
        "        });\n"
        "        label.addEventListener(\"pointermove\", function(evt) { moveHoverTip(evt.clientX, evt.clientY); });\n"
        "        label.addEventListener(\"pointerleave\", function() { hideHoverTip(); });\n"
        "      }\n"
        "    }\n"
        "    function updateActiveLabelStates() {\n"
        "      var colLabels = colLabelNodes();\n"
        "      var searchEnabled = !!safetySearchText();\n"
        "      for (var i = 0; i < colLabels.length; i++) {\n"
        "        var colLabel = colLabels[i];\n"
        "        var rawName = rawColLabel(colLabel);\n"
        "        var colMetaItem = lookupColLabelMeta(rawName);\n"
        "        var colActive = !!selectedColLabel && rawColLabel(colLabel) === displayLabelForPayload(selectedColLabel);\n"
        "        var searchMatch = targetMatchesSafetySearch(colMetaItem);\n"
        "        colLabel.classList.toggle(\"cg-active-label\", colActive);\n"
        "        colLabel.setAttribute(\"aria-pressed\", colActive ? \"true\" : \"false\");\n"
        "        colLabel.classList.toggle(\"cg-safety-search-hit\", searchEnabled && searchMatch);\n"
        "        if (targetOrganizationMode === \"none\" || colActive) {\n"
        "          colLabel.style.fill = \"\";\n"
        "          colLabel.style.fontWeight = \"\";\n"
        "        } else {\n"
        "          var groupName = targetOrganizationValue(rawName, targetOrganizationMode) || \"Unassigned\";\n"
        "          var orgColor = organizationColorForValue(groupName);\n"
        "          colLabel.style.fill = orgColor;\n"
        "          colLabel.style.fontWeight = \"700\";\n"
        "        }\n"
        "        colLabel.style.opacity = searchEnabled ? (searchMatch ? \"1\" : \"0.38\") : \"\";\n"
        "      }\n"
        "      var rowLabels = rowLabelGroups();\n"
        "      var motifEnabled = !!motifSearchText();\n"
        "      for (var j = 0; j < rowLabels.length; j++) {\n"
        "        var rowLabel = rowLabels[j];\n"
        "        var rowName = rawRowGroupLabel(rowLabel);\n"
        "        var rowActive = !!selectedLigand && rowName === selectedLigand;\n"
        "        var rowMetaItem = lookupRowLabelMeta(rowName);\n"
        "        var motifMatch = ligandMatchesMotifSearch(rowMetaItem);\n"
        "        rowLabel.classList.toggle(\"cg-active-label\", rowActive);\n"
        "        rowLabel.setAttribute(\"aria-pressed\", rowActive ? \"true\" : \"false\");\n"
        "        rowLabel.classList.toggle(\"cg-motif-search-hit\", motifEnabled && motifMatch);\n"
        "        if (ligandOrganizationMode === \"none\" || rowActive) {\n"
        "          rowLabel.style.fill = \"\";\n"
        "          rowLabel.style.fontWeight = \"\";\n"
        "        } else {\n"
        "          var ligandGroup = ligandOrganizationValue(rowName, ligandOrganizationMode) || \"Other / Unassigned\";\n"
        "          var ligandColor = ligandOrganizationColorForValue(ligandGroup);\n"
        "          rowLabel.style.fill = ligandColor;\n"
        "          rowLabel.style.fontWeight = \"700\";\n"
        "        }\n"
        "        rowLabel.style.opacity = motifEnabled ? (motifMatch ? \"1\" : \"0.38\") : \"\";\n"
        "      }\n"
        "    }\n"
        "    function parseColor(color) {\n"
        "      var value = String(color || \"\").trim();\n"
        "      if (!value) return null;\n"
        "      var hex = value.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);\n"
        "      if (hex) {\n"
        "        var raw = hex[1];\n"
        "        if (raw.length === 3) raw = raw.charAt(0) + raw.charAt(0) + raw.charAt(1) + raw.charAt(1) + raw.charAt(2) + raw.charAt(2);\n"
        "        return [parseInt(raw.slice(0, 2), 16), parseInt(raw.slice(2, 4), 16), parseInt(raw.slice(4, 6), 16)];\n"
        "      }\n"
        "      var rgb = value.match(/^rgba?\\(([^)]+)\\)$/i);\n"
        "      if (!rgb) return null;\n"
        "      var parts = rgb[1].split(\",\");\n"
        "      if (parts.length < 3) return null;\n"
        "      return [Math.max(0, Math.min(255, Number(parts[0]))), Math.max(0, Math.min(255, Number(parts[1]))), Math.max(0, Math.min(255, Number(parts[2])))];\n"
        "    }\n"
        "    function textFillForColor(color) {\n"
        "      var rgb = parseColor(color);\n"
        "      if (!rgb) return \"#172117\";\n"
        "      var luminance = (0.2126 * rgb[0] + 0.7152 * rgb[1] + 0.0722 * rgb[2]) / 255;\n"
        "      return luminance < 0.58 ? \"#ffffff\" : \"#172117\";\n"
        "    }\n"
        "    function getTileBox(tile) {\n"
        "      if (!tile || typeof tile.getBBox !== \"function\") return null;\n"
        "      try {\n"
        "        var box = tile.getBBox();\n"
        "        if (!box || !Number.isFinite(box.width) || !Number.isFinite(box.height)) return null;\n"
        "        return box;\n"
        "      } catch (_err) {\n"
        "        return null;\n"
        "      }\n"
        "    }\n"
        "    function ensureCellValueLayer() {\n"
        "      var clustGroup = container.querySelector(\".clust_group\");\n"
        "      if (!clustGroup) return null;\n"
        "      var existing = clustGroup.querySelector(\".cg-cell-value-layer\");\n"
        "      if (existing && existing.parentNode) existing.parentNode.removeChild(existing);\n"
        "      var layer = document.createElementNS(\"http://www.w3.org/2000/svg\", \"g\");\n"
        "      layer.setAttribute(\"class\", \"cg-cell-value-layer\");\n"
        "      layer.setAttribute(\"pointer-events\", \"none\");\n"
        "      clustGroup.appendChild(layer);\n"
        "      return layer;\n"
        "    }\n"
        "    function renderCellValueOverlay() {\n"
        "      var layer = ensureCellValueLayer();\n"
        "      if (!layer) return;\n"
        "      var tiles = container.querySelectorAll(\".tile\");\n"
        "      var seen = Object.create(null);\n"
        "      for (var i = 0; i < tiles.length; i++) {\n"
        "        var tile = tiles[i];\n"
        "        var data = tile.__data__ || {};\n"
        "        var rowName = data.row_name || data.row || \"\";\n"
        "        var colName = data.col_name || data.col || \"\";\n"
        "        var key = tileKey(rowName, colName);\n"
        "        if (seen[key]) continue;\n"
        "        seen[key] = true;\n"
        "        var meta = lookupMeta(rowName, colName);\n"
        "        if (!meta) continue;\n"
        "        var valueText = activeValueText(meta);\n"
        "        if (!valueText) continue;\n"
        "        var box = getTileBox(tile);\n"
        "        if (!box || box.width < cellValueMinSide || box.height < cellValueMinSide) continue;\n"
        "        var minWidthForText = Math.max(cellValueMinSide, valueText.length * 6.2);\n"
        "        if (box.width < minWidthForText) continue;\n"
        "        var textEl = document.createElementNS(\"http://www.w3.org/2000/svg\", \"text\");\n"
        "        var fontSize = Math.max(8, Math.min(14, Math.min(box.height * 0.52, box.width / Math.max(2.2, valueText.length * 0.62))));\n"
        "        textEl.setAttribute(\"x\", String(box.x + box.width / 2));\n"
        "        textEl.setAttribute(\"y\", String(box.y + box.height / 2));\n"
        "        textEl.setAttribute(\"text-anchor\", \"middle\");\n"
        "        textEl.setAttribute(\"dominant-baseline\", \"middle\");\n"
        "        textEl.setAttribute(\"font-size\", fontSize.toFixed(2));\n"
        "        var fillColor = tile.getAttribute(\"fill\") || tile.style.fill || \"#ffffff\";\n"
        "        textEl.setAttribute(\"fill\", textFillForColor(fillColor));\n"
        "        textEl.textContent = valueText;\n"
        "        layer.appendChild(textEl);\n"
        "      }\n"
        "      debugLine(\"[heatmap.debug] cell_value_overlay_count=\" + layer.childNodes.length);\n"
        "    }\n"
        "    function resolveInputDomain() {\n"
        "      if (!activeBreaks) return 0;\n"
        "      var minAbs = Math.abs(Number(activeBreaks.scale_min || 0));\n"
        "      var maxAbs = Math.abs(Number(activeBreaks.scale_max || 0));\n"
        "      var domain = Math.max(minAbs, maxAbs);\n"
        "      return Number.isFinite(domain) && domain > 0 ? domain : 0;\n"
        "    }\n"
        "    function activeVizData() {\n"
        "      var payload = baseVizData();\n"
        "      normalizeSelectionState(payload);\n"
        "      var rowIndices = derivedRowIndices(payload);\n"
        "      var colIndices = derivedColIndices(payload);\n"
        "      updateViewSummary(payload, rowIndices, colIndices);\n"
        "      renderOrganizationStrip(payload, colIndices);\n"
        "      var rowNodes = reindexNodes(rowIndices.map(function(rowIndex) { return cloneJson(payload.row_nodes[rowIndex]); }));\n"
        "      var colNodes = reindexNodes(colIndices.map(function(colIndex) { return cloneJson(payload.col_nodes[colIndex]); }));\n"
        "      var cloned = {\n"
        "        row_nodes: rowNodes,\n"
        "        col_nodes: colNodes,\n"
        "        links: [],\n"
        "        mat: rowIndices.map(function(rowIndex) {\n"
        "          return colIndices.map(function(colIndex) {\n"
        "            var row = Array.isArray(payload.mat) ? payload.mat[rowIndex] : null;\n"
        "            return Array.isArray(row) ? row[colIndex] : null;\n"
        "          });\n"
        "        }),\n"
        "        cat_colors: cloneJson(payload.cat_colors || {}),\n"
        "        views: []\n"
        "      };\n"
        "      return cloned;\n"
        "    }\n"
        "    function setSvgSize(svg, width, height) {\n"
        "      if (!svg) return;\n"
        "      svg.setAttribute(\"viewBox\", \"0 0 \" + width + \" \" + height);\n"
        "      svg.setAttribute(\"width\", \"100%\");\n"
        "      svg.setAttribute(\"height\", String(height));\n"
        "      while (svg.firstChild) svg.removeChild(svg.firstChild);\n"
        "    }\n"
        "    function analysisCanvas(kind) {\n"
        "      return document.querySelector('[data-analysis-canvas=\"' + kind + '\"]');\n"
        "    }\n"
        "    function analysisTitle(kind) {\n"
        "      return document.querySelector('[data-analysis-title=\"' + kind + '\"]');\n"
        "    }\n"
        "    function analysisSubtitle(kind) {\n"
        "      return document.querySelector('[data-analysis-subtitle=\"' + kind + '\"]');\n"
        "    }\n"
        "    function analysisNote(kind) {\n"
        "      return document.querySelector('[data-analysis-note=\"' + kind + '\"]');\n"
        "    }\n"
        "    function setAnalysisText(kind, title, subtitle, note) {\n"
        "      var titleEl = analysisTitle(kind);\n"
        "      var subtitleEl = analysisSubtitle(kind);\n"
        "      var noteEl = analysisNote(kind);\n"
        "      if (titleEl) titleEl.textContent = title || \"\";\n"
        "      if (subtitleEl) subtitleEl.textContent = subtitle || \"\";\n"
        "      if (noteEl) noteEl.textContent = note || \"\";\n"
        "    }\n"
        "    function visibleNameMap(nodes) {\n"
        "      var out = Object.create(null);\n"
        "      for (var i = 0; i < nodes.length; i++) out[cgKey(nodes[i].name || \"\")] = true;\n"
        "      return out;\n"
        "    }\n"
        "    function setAnalysisTab(tabName) {\n"
        "      activeAnalysisTab = tabName;\n"
        "      var tabButtons = document.querySelectorAll('[data-analysis-tab]');\n"
        "      for (var i = 0; i < tabButtons.length; i++) tabButtons[i].classList.toggle(\"is-active\", tabButtons[i].getAttribute(\"data-analysis-tab\") === tabName);\n"
        "      var views = document.querySelectorAll('[data-analysis-view]');\n"
        "      for (var j = 0; j < views.length; j++) views[j].classList.toggle(\"is-active\", views[j].getAttribute(\"data-analysis-view\") === tabName);\n"
        "    }\n"
        "    function updateAnalysisSubtabStates() {\n"
        "      var scatterButtons = document.querySelectorAll('[data-scatter-mode]');\n"
        "      for (var i = 0; i < scatterButtons.length; i++) scatterButtons[i].classList.toggle(\"is-active\", scatterButtons[i].getAttribute(\"data-scatter-mode\") === activeScatterMode);\n"
        "      var rankModeButtons = document.querySelectorAll('[data-rank-mode]');\n"
        "      for (var j = 0; j < rankModeButtons.length; j++) rankModeButtons[j].classList.toggle(\"is-active\", rankModeButtons[j].getAttribute(\"data-rank-mode\") === activeRankMode);\n"
        "      var rankMetricButtons = document.querySelectorAll('[data-rank-metric]');\n"
        "      for (var k = 0; k < rankMetricButtons.length; k++) rankMetricButtons[k].classList.toggle(\"is-active\", rankMetricButtons[k].getAttribute(\"data-rank-metric\") === activeRankMetric);\n"
        "    }\n"
        "    function metricPointData(mode) {\n"
        "      var source = mode === \"cols\" ? (currentAnalysis && currentAnalysis.colMetrics) : (currentAnalysis && currentAnalysis.rowMetrics);\n"
        "      var names = mode === \"cols\" ? allColNames() : allRowNames();\n"
        "      return names.map(function(name) {\n"
        "        var meta = source && source[name] ? source[name] : {};\n"
        "        return {\n"
        "          name: name,\n"
        "          x: asNumber(meta.hit_fraction),\n"
        "          y: asNumber(meta.promiscuity_z),\n"
        "          entropy: asNumber(meta.entropy),\n"
        "          meta: mode === \"cols\" ? lookupColLabelMeta(name) : lookupRowLabelMeta(name)\n"
        "        };\n"
        "      }).filter(function(item) { return item.x != null && item.y != null; });\n"
        "    }\n"
        "    function drawAxisTicks(svg, origin, length, ticks, vertical) {\n"
        "      for (var i = 0; i < ticks.length; i++) {\n"
        "        var tick = ticks[i];\n"
        "        var line = document.createElementNS(\"http://www.w3.org/2000/svg\", \"line\");\n"
        "        var text = document.createElementNS(\"http://www.w3.org/2000/svg\", \"text\");\n"
        "        if (vertical) {\n"
        "          line.setAttribute(\"x1\", String(origin.x - 4));\n"
        "          line.setAttribute(\"x2\", String(origin.x));\n"
        "          line.setAttribute(\"y1\", String(tick.pos));\n"
        "          line.setAttribute(\"y2\", String(tick.pos));\n"
        "          text.setAttribute(\"x\", String(origin.x - 8));\n"
        "          text.setAttribute(\"y\", String(tick.pos + 4));\n"
        "          text.setAttribute(\"text-anchor\", \"end\");\n"
        "        } else {\n"
        "          line.setAttribute(\"x1\", String(tick.pos));\n"
        "          line.setAttribute(\"x2\", String(tick.pos));\n"
        "          line.setAttribute(\"y1\", String(origin.y));\n"
        "          line.setAttribute(\"y2\", String(origin.y + 4));\n"
        "          text.setAttribute(\"x\", String(tick.pos));\n"
        "          text.setAttribute(\"y\", String(origin.y + 18));\n"
        "          text.setAttribute(\"text-anchor\", \"middle\");\n"
        "        }\n"
        "        line.setAttribute(\"stroke\", \"#63745c\");\n"
        "        line.setAttribute(\"stroke-width\", \"1\");\n"
        "        text.setAttribute(\"font-size\", \"11\");\n"
        "        text.setAttribute(\"fill\", \"#516151\");\n"
        "        text.textContent = tick.label;\n"
        "        svg.appendChild(line);\n"
        "        svg.appendChild(text);\n"
        "      }\n"
        "    }\n"
        "    function drawAxisLabel(svg, x, y, label, rotateDeg) {\n"
        "      var text = document.createElementNS(\"http://www.w3.org/2000/svg\", \"text\");\n"
        "      text.setAttribute(\"x\", String(x));\n"
        "      text.setAttribute(\"y\", String(y));\n"
        "      text.setAttribute(\"font-size\", \"12\");\n"
        "      text.setAttribute(\"font-weight\", \"700\");\n"
        "      text.setAttribute(\"fill\", \"#243a2a\");\n"
        "      text.setAttribute(\"text-anchor\", \"middle\");\n"
        "      if (rotateDeg) text.setAttribute(\"transform\", \"rotate(\" + rotateDeg + \" \" + x + \" \" + y + \")\");\n"
        "      text.textContent = label;\n"
        "      svg.appendChild(text);\n"
        "    }\n"
        "    function bindSvgHover(node, linesBuilder) {\n"
        "      if (!node) return;\n"
        "      node.addEventListener(\"pointerenter\", function(evt) { showHoverTip(linesBuilder(), evt.clientX, evt.clientY); });\n"
        "      node.addEventListener(\"pointermove\", function(evt) { moveHoverTip(evt.clientX, evt.clientY); });\n"
        "      node.addEventListener(\"pointerleave\", function() { hideHoverTip(); });\n"
        "    }\n"
        "    function renderScatterPanel() {\n"
        "      var svg = analysisCanvas(\"scatter\");\n"
        "      if (!svg) return;\n"
        "      if (activeScatterMode !== \"rows\") activeScatterMode = \"rows\";\n"
        "      var points = metricPointData(activeScatterMode);\n"
        "      var width = Math.max(640, Math.round((svg.parentNode && svg.parentNode.clientWidth) || 960));\n"
        "      var height = 390;\n"
        "      setSvgSize(svg, width, height);\n"
        "      setAnalysisText(\"scatter\", \"Promiscuity vs Significant Hit Fraction\", entityLabel(activeScatterMode) + \" | Threshold: \" + thresholdDescriptor() + \" | Each point is one \" + entityLabel(activeScatterMode).toLowerCase().slice(0, -1), \"X-axis: significant hit fraction. Y-axis: promiscuity z-score. Hover points for entropy and item metadata.\");\n"
        "      if (!points.length) return;\n"
        "      var pad = { left: 68, right: 22, top: 24, bottom: 58 };\n"
        "      var xMax = Math.max.apply(null, points.map(function(item) { return item.x; }).concat([0.01]));\n"
        "      var yVals = points.map(function(item) { return item.y; });\n"
        "      var yMin = Math.min.apply(null, yVals.concat([0]));\n"
        "      var yMax = Math.max.apply(null, yVals.concat([0]));\n"
        "      var innerW = width - pad.left - pad.right;\n"
        "      var innerH = height - pad.top - pad.bottom;\n"
        "      function xScale(value) { return pad.left + (value / Math.max(1e-9, xMax)) * innerW; }\n"
        "      function yScale(value) { return pad.top + innerH - ((value - yMin) / Math.max(1e-9, yMax - yMin || 1)) * innerH; }\n"
        "      var axis = document.createElementNS(\"http://www.w3.org/2000/svg\", \"g\");\n"
        "      axis.innerHTML = '<line x1=\"' + pad.left + '\" y1=\"' + (pad.top + innerH) + '\" x2=\"' + (pad.left + innerW) + '\" y2=\"' + (pad.top + innerH) + '\" stroke=\"#63745c\"/><line x1=\"' + pad.left + '\" y1=\"' + pad.top + '\" x2=\"' + pad.left + '\" y2=\"' + (pad.top + innerH) + '\" stroke=\"#63745c\"/>';\n"
        "      svg.appendChild(axis);\n"
        "      var xTicks = [];\n"
        "      for (var xt = 0; xt <= 4; xt++) { var xv = (xMax * xt) / 4; xTicks.push({ pos: xScale(xv), label: formatPercent(xv, 0) }); }\n"
        "      var yTicks = [];\n"
        "      for (var yt = 0; yt <= 4; yt++) { var yv = yMin + ((yMax - yMin || 1) * yt) / 4; yTicks.push({ pos: yScale(yv), label: formatMetric(yv, 2) }); }\n"
        "      drawAxisTicks(svg, { x: pad.left, y: pad.top + innerH }, innerW, xTicks, false);\n"
        "      drawAxisTicks(svg, { x: pad.left, y: pad.top }, innerH, yTicks, true);\n"
        "      drawAxisLabel(svg, pad.left + innerW / 2, height - 16, \"Significant hit fraction (%)\", 0);\n"
        "      drawAxisLabel(svg, 18, pad.top + innerH / 2, \"Promiscuity z-score\", -90);\n"
        "      for (var i = 0; i < points.length; i++) {\n"
        "        var point = points[i];\n"
        "        var circle = document.createElementNS(\"http://www.w3.org/2000/svg\", \"circle\");\n"
        "        circle.setAttribute(\"cx\", String(xScale(point.x)));\n"
        "        circle.setAttribute(\"cy\", String(yScale(point.y)));\n"
        "        circle.setAttribute(\"r\", \"5\");\n"
        "        circle.setAttribute(\"fill\", activeScatterMode === \"cols\" ? \"#245f89\" : \"#2c6b4d\");\n"
        "        circle.setAttribute(\"fill-opacity\", \"0.78\");\n"
        "        circle.style.cursor = \"pointer\";\n"
        "        bindSvgHover(circle, (function(entry) { return function() { var lines = [activeScatterMode === \"cols\" ? (\"pdb: \" + String(entry.meta.pdb || \"\")) : (\"ligand: \" + entry.name), \"promiscuity_z: \" + formatMetric(entry.y, 6), \"hit_fraction: \" + formatPercent(entry.x, 2), \"entropy: \" + formatMetric(entry.entropy, 6)]; if (activeScatterMode === \"cols\") { if (entry.meta.target_name) lines.splice(1, 0, \"target_name: \" + String(entry.meta.target_name)); if (entry.meta.variant_ph) lines.splice(2, 0, \"variant/pH: \" + String(entry.meta.variant_ph)); if (entry.meta.protein_family) lines.push(\"protein_family: \" + String(entry.meta.protein_family)); appendTargetSafetyLines(lines, entry.meta); } return lines; }; })(point));\n"
        "        circle.addEventListener(\"click\", (function(entry) { return function(evt) { evt.preventDefault(); evt.stopPropagation(); if (activeScatterMode === \"cols\") { activatePdbSelection(entry.name, String(entry.meta.pdb || \"\")); } else { activateLigandSort(entry.name); } renderCurrentMode(); }; })(point));\n"
        "        svg.appendChild(circle);\n"
        "      }\n"
        "    }\n"
        "    function rankingEntries() {\n"
        "      if (activeRankMode !== \"rows\") activeRankMode = \"rows\";\n"
        "      var source = activeRankMode === \"cols\" ? (currentAnalysis && currentAnalysis.colMetrics) : (currentAnalysis && currentAnalysis.rowMetrics);\n"
        "      var names = activeRankMode === \"cols\" ? allColNames() : allRowNames();\n"
        "      return names.map(function(name) {\n"
        "        var meta = source && source[name] ? source[name] : {};\n"
        "        return {\n"
        "          name: name,\n"
        "          value: asNumber(meta[activeRankMetric]),\n"
        "          meta: activeRankMode === \"cols\" ? lookupColLabelMeta(name) : lookupRowLabelMeta(name)\n"
        "        };\n"
        "      }).filter(function(entry) { return entry.value != null; }).sort(function(a, b) {\n"
        "        if (b.value !== a.value) return b.value - a.value;\n"
        "        return a.name < b.name ? -1 : (a.name > b.name ? 1 : 0);\n"
        "      });\n"
        "    }\n"
        "    function renderRankingPanel() {\n"
        "      var svg = analysisCanvas(\"rank\");\n"
        "      if (!svg) return;\n"
        "      var entries = rankingEntries().slice(0, 20);\n"
        "      var width = Math.max(640, Math.round((svg.parentNode && svg.parentNode.clientWidth) || 960));\n"
        "      var height = Math.max(360, 68 + entries.length * 16);\n"
        "      setSvgSize(svg, width, height);\n"
        "      setAnalysisText(\"rank\", \"Ranking by \" + metricLabel(activeRankMetric), entityLabel(activeRankMode) + \" | Threshold: \" + thresholdDescriptor() + \" | Sorted descending\", \"Showing the top 20 items for readability. Hover bars for full metadata.\");\n"
        "      if (!entries.length) return;\n"
        "      var maxValue = Math.max.apply(null, entries.map(function(entry) { return entry.value; }).concat([1]));\n"
        "      var pad = { left: 220, right: 32, top: 18, bottom: 42 };\n"
        "      var innerW = width - pad.left - pad.right;\n"
        "      var innerH = height - pad.top - pad.bottom;\n"
        "      var axis = document.createElementNS(\"http://www.w3.org/2000/svg\", \"g\");\n"
        "      axis.innerHTML = '<line x1=\"' + pad.left + '\" y1=\"' + (pad.top + innerH) + '\" x2=\"' + (pad.left + innerW) + '\" y2=\"' + (pad.top + innerH) + '\" stroke=\"#63745c\"/><line x1=\"' + pad.left + '\" y1=\"' + pad.top + '\" x2=\"' + pad.left + '\" y2=\"' + (pad.top + innerH) + '\" stroke=\"#63745c\"/>';\n"
        "      svg.appendChild(axis);\n"
        "      var xTicks = [];\n"
        "      for (var xt = 0; xt <= 4; xt++) { var xv = (maxValue * xt) / 4; xTicks.push({ pos: pad.left + (xv / Math.max(1e-9, maxValue)) * innerW, label: formatMetricValue(activeRankMetric, xv) }); }\n"
        "      drawAxisTicks(svg, { x: pad.left, y: pad.top + innerH }, innerW, xTicks, false);\n"
        "      drawAxisLabel(svg, pad.left + innerW / 2, height - 12, metricLabel(activeRankMetric), 0);\n"
        "      drawAxisLabel(svg, 24, pad.top + innerH / 2, activeRankMode === \"cols\" ? \"Target\" : \"Ligand\", -90);\n"
        "      var rowStep = innerH / Math.max(1, entries.length);\n"
        "      for (var j = 0; j < entries.length; j++) {\n"
        "        var entry = entries[j];\n"
        "        var label = activeRankMode === \"cols\" ? String(entry.meta.pdb || targetShortName(entry.name, entry.meta)) : entry.name;\n"
        "        var y = pad.top + j * rowStep + rowStep * 0.65;\n"
        "        var w = (entry.value / Math.max(1e-9, maxValue)) * innerW;\n"
        "        var bar = document.createElementNS(\"http://www.w3.org/2000/svg\", \"rect\");\n"
        "        var text = document.createElementNS(\"http://www.w3.org/2000/svg\", \"text\");\n"
        "        bar.setAttribute(\"x\", String(pad.left));\n"
        "        bar.setAttribute(\"y\", String(y - 9));\n"
        "        bar.setAttribute(\"width\", String(Math.max(0, w)));\n"
        "        bar.setAttribute(\"height\", \"12\");\n"
        "        bar.setAttribute(\"rx\", \"4\");\n"
        "        bar.setAttribute(\"fill\", activeRankMode === \"cols\" ? \"#245f89\" : \"#2c6b4d\");\n"
        "        bar.setAttribute(\"fill-opacity\", \"0.84\");\n"
        "        bar.style.cursor = \"pointer\";\n"
        "        text.setAttribute(\"x\", String(pad.left - 8));\n"
        "        text.setAttribute(\"y\", String(y + 4));\n"
        "        text.setAttribute(\"text-anchor\", \"end\");\n"
        "        text.setAttribute(\"font-size\", \"11\");\n"
        "        text.setAttribute(\"fill\", \"#334533\");\n"
        "        text.textContent = label;\n"
        "        bindSvgHover(bar, (function(item) { return function() { var lines = [activeRankMode === \"cols\" ? (\"pdb: \" + String(item.meta.pdb || \"\")) : (\"ligand: \" + item.name), metricLabel(activeRankMetric) + \": \" + formatMetricValue(activeRankMetric, item.value)]; if (activeRankMode === \"cols\") { if (item.meta.target_name) lines.splice(1, 0, \"target_name: \" + String(item.meta.target_name)); if (item.meta.variant_ph) lines.splice(2, 0, \"variant/pH: \" + String(item.meta.variant_ph)); if (item.meta.protein_family) lines.push(\"protein_family: \" + String(item.meta.protein_family)); appendTargetSafetyLines(lines, item.meta); } appendPromiscuityLines(lines, item.meta); return lines; }; })(entry));\n"
        "        bar.addEventListener(\"click\", (function(item) { return function(evt) { evt.preventDefault(); evt.stopPropagation(); if (activeRankMode === \"cols\") activatePdbSelection(item.name, String(item.meta.pdb || \"\")); else activateLigandSort(item.name); renderCurrentMode(); }; })(entry));\n"
        "        bindSvgHover(text, (function(item) { return function() { var lines = [activeRankMode === \"cols\" ? (\"pdb: \" + String(item.meta.pdb || \"\")) : (\"ligand: \" + item.name), metricLabel(activeRankMetric) + \": \" + formatMetricValue(activeRankMetric, item.value)]; if (activeRankMode === \"cols\") { if (item.meta.target_name) lines.splice(1, 0, \"target_name: \" + String(item.meta.target_name)); if (item.meta.variant_ph) lines.splice(2, 0, \"variant/pH: \" + String(item.meta.variant_ph)); if (item.meta.protein_family) lines.push(\"protein_family: \" + String(item.meta.protein_family)); appendTargetSafetyLines(lines, item.meta); } appendPromiscuityLines(lines, item.meta); return lines; }; })(entry));\n"
        "        svg.appendChild(bar);\n"
        "        svg.appendChild(text);\n"
        "      }\n"
        "    }\n"
        "    function renderNetworkPanel(networkData) {\n"
        "      var svg = analysisCanvas(\"network\");\n"
        "      var noteEl = analysisNote(\"network\");\n"
        "      if (!svg) return;\n"
        "      var width = Math.max(640, Math.round((svg.parentNode && svg.parentNode.clientWidth) || 960));\n"
        "      var height = 380;\n"
        "      setSvgSize(svg, width, height);\n"
        "      setAnalysisText(\"network\", \"Significant ligand-target network\", \"Current threshold: \" + thresholdDescriptor() + \" | Visible nodes follow the current heatmap state\", \"Edge color shows the sign of Atlas score. Only the strongest edges are shown when the network is dense.\");\n"
        "      if (noteEl) noteEl.textContent = \"\";\n"
        "      var visibleRows = visibleNameMap(networkData && Array.isArray(networkData.row_nodes) ? networkData.row_nodes : []);\n"
        "      var visibleCols = visibleNameMap(networkData && Array.isArray(networkData.col_nodes) ? networkData.col_nodes : []);\n"
        "      var edges = (currentAnalysis && Array.isArray(currentAnalysis.edges) ? currentAnalysis.edges : []).filter(function(edge) { return visibleRows[edge.row] && visibleCols[edge.col]; });\n"
        "      if (!edges.length) { if (noteEl) noteEl.textContent = \"No significant ligand-target edges at the current threshold.\"; return; }\n"
        "      edges.sort(function(a, b) { return b.z - a.z; });\n"
        "      var limitedEdges = edges.slice(0, 220);\n"
        "      if (noteEl && edges.length > limitedEdges.length) noteEl.textContent = \"Showing top \" + limitedEdges.length + \" significant edges for readability.\";\n"
        "      var rowNames = Object.keys(visibleRows);\n"
        "      var colNames = Object.keys(visibleCols);\n"
        "      var rowPos = Object.create(null);\n"
        "      var colPos = Object.create(null);\n"
        "      for (var i = 0; i < rowNames.length; i++) rowPos[rowNames[i]] = 26 + (i * Math.max(18, (height - 52) / Math.max(1, rowNames.length - 1)));\n"
        "      for (var j = 0; j < colNames.length; j++) colPos[colNames[j]] = 26 + (j * Math.max(18, (height - 52) / Math.max(1, colNames.length - 1)));\n"
        "      for (var e = 0; e < limitedEdges.length; e++) {\n"
        "        var edge = limitedEdges[e];\n"
        "        var line = document.createElementNS(\"http://www.w3.org/2000/svg\", \"line\");\n"
        "        line.setAttribute(\"x1\", \"150\"); line.setAttribute(\"x2\", String(width - 150));\n"
        "        line.setAttribute(\"y1\", String(rowPos[edge.row] || 26)); line.setAttribute(\"y2\", String(colPos[edge.col] || 26));\n"
        "        line.setAttribute(\"stroke\", edge.z >= 0 ? \"#b2182b\" : \"#2166ac\");\n"
        "        line.setAttribute(\"stroke-opacity\", String(Math.max(0.18, Math.min(0.78, Math.abs(edge.z) / 6))));\n"
        "        bindSvgHover(line, (function(entry) { return function() { return [\"ligand: \" + entry.row, \"target: \" + targetShortName(entry.col, lookupMeta(entry.row, entry.col)), \"Atlas score: \" + formatMetric(entry.z, 6), \"pct_rank: \" + formatMetric(entry.pct_rank, 6)]; }; })(edge));\n"
        "        svg.appendChild(line);\n"
        "      }\n"
        "      for (var r = 0; r < rowNames.length; r++) {\n"
        "        var rowLabel = document.createElementNS(\"http://www.w3.org/2000/svg\", \"text\");\n"
        "        rowLabel.setAttribute(\"x\", \"12\"); rowLabel.setAttribute(\"y\", String(rowPos[rowNames[r]] || 26)); rowLabel.setAttribute(\"font-size\", \"11\"); rowLabel.setAttribute(\"fill\", \"#234f39\"); rowLabel.textContent = rowNames[r]; rowLabel.style.cursor = \"pointer\";\n"
        "        bindSvgHover(rowLabel, (function(name) { return function() { var meta = lookupRowLabelMeta(name); var lines = [\"ligand: \" + name]; appendLigandAnnotationLines(lines, meta); appendPromiscuityLines(lines, meta); return lines; }; })(rowNames[r]));\n"
        "        rowLabel.addEventListener(\"click\", (function(name) { return function(evt) { evt.preventDefault(); evt.stopPropagation(); activateLigandSort(name); renderCurrentMode(); }; })(rowNames[r]));\n"
        "        svg.appendChild(rowLabel);\n"
        "      }\n"
        "      for (var c = 0; c < colNames.length; c++) {\n"
        "        var colLabel = document.createElementNS(\"http://www.w3.org/2000/svg\", \"text\");\n"
        "        var colMetaItem = lookupColLabelMeta(colNames[c]);\n"
        "        colLabel.setAttribute(\"x\", String(width - 138)); colLabel.setAttribute(\"y\", String(colPos[colNames[c]] || 26)); colLabel.setAttribute(\"font-size\", \"11\"); colLabel.setAttribute(\"fill\", \"#1f5578\"); colLabel.textContent = String(colMetaItem.pdb || targetShortName(colNames[c], null)); colLabel.style.cursor = \"pointer\";\n"
        "        var networkColor = organizationColorForValue(targetOrganizationValue(colNames[c], targetOrganizationMode) || \"Unassigned\");\n"
        "        if (targetOrganizationMode !== \"none\") { colLabel.setAttribute(\"fill\", networkColor); colLabel.setAttribute(\"font-weight\", \"700\"); }\n"
        "        bindSvgHover(colLabel, (function(name) { return function() { var meta = lookupColLabelMeta(name); var lines = [\"pdb: \" + String(meta.pdb || \"\"), \"target_name: \" + String(meta.target_name || \"\")]; if (meta.variant_ph) lines.push(\"variant/pH: \" + String(meta.variant_ph)); if (meta.protein_family) lines.push(\"protein_family: \" + String(meta.protein_family)); appendTargetSafetyLines(lines, meta); appendPromiscuityLines(lines, meta); return lines; }; })(colNames[c]));\n"
        "        colLabel.addEventListener(\"click\", (function(name, pdb) { return function(evt) { evt.preventDefault(); evt.stopPropagation(); activatePdbSelection(name, pdb); renderCurrentMode(); }; })(colNames[c], String(colMetaItem.pdb || \"\")));\n"
        "        svg.appendChild(colLabel);\n"
        "      }\n"
        "    }\n"
        "    function renderAnalysisPanels(networkData) {\n"
        "      updateAnalysisSubtabStates();\n"
        "      setAnalysisTab(activeAnalysisTab);\n"
        "      renderScatterPanel();\n"
        "      renderRankingPanel();\n"
        "      renderNetworkPanel(networkData || activeVizData());\n"
        "    }\n"
        f"{report_extras.script_block}\n"
        "    function bindAnalysisControls() {\n"
        "      if (container.getAttribute(\"data-cg-analysis-bound\") === \"1\") return;\n"
        "      container.setAttribute(\"data-cg-analysis-bound\", \"1\");\n"
        "      activeScatterMode = \"rows\";\n"
        "      activeRankMode = \"rows\";\n"
        "      if (thresholdRangeEl) thresholdRangeEl.addEventListener(\"input\", function() { activeThreshold = Math.max(0.001, Math.min(0.1, Number(thresholdRangeEl.value) || activeThreshold)); renderCurrentMode(); });\n"
        "      if (thresholdPctEl) thresholdPctEl.addEventListener(\"click\", function() { activeThresholdMode = \"pct\"; renderCurrentMode(); });\n"
        "      if (thresholdFdrEl) thresholdFdrEl.addEventListener(\"click\", function() { activeThresholdMode = \"fdr\"; renderCurrentMode(); });\n"
        "      if (thresholdScorchFdrEl) thresholdScorchFdrEl.addEventListener(\"click\", function() { activeThresholdMode = \"scorch_fdr\"; renderCurrentMode(); });\n"
        "      if (thresholdScorchRelaxedFdrEl) thresholdScorchRelaxedFdrEl.addEventListener(\"click\", function() { activeThresholdMode = \"scorch_fdr_relaxed\"; renderCurrentMode(); });\n"
        "      if (safetySearchInputEl) safetySearchInputEl.addEventListener(\"input\", function() { activeSafetySearch = String(safetySearchInputEl.value || \"\").trim(); renderAnnotationPanels(); updateActiveLabelStates(); updateViewSummary(baseVizData()); });\n"
        "      if (safetySearchClearEl) safetySearchClearEl.addEventListener(\"click\", function() { activeSafetySearch = \"\"; if (safetySearchInputEl) safetySearchInputEl.value = \"\"; renderAnnotationPanels(); updateActiveLabelStates(); updateViewSummary(baseVizData()); });\n"
        "      if (resetButtonEl) resetButtonEl.addEventListener(\"click\", function() { activeThreshold = Math.max(0.001, Math.min(0.1, Number(analysisMeta.default_threshold_pct_rank) || 0.01)); activeThresholdMode = \"pct\"; topKDisplay = Math.max(1, Math.round(Number(analysisMeta.default_top_k) || 100)); targetOrganizationMode = String((analysisMeta.target_organization && analysisMeta.target_organization.default_mode) || \"none\"); targetOrganizationCategory = \"\"; ligandOrganizationMode = String((analysisMeta.ligand_organization && analysisMeta.ligand_organization.default_mode) || \"none\"); if (typeof ligandOrganizationCategory !== \"undefined\") ligandOrganizationCategory = \"\"; activeSafetySearch = \"\"; activeMotifSearch = \"\"; if (safetySearchInputEl) safetySearchInputEl.value = \"\"; if (motifSearchInputEl) motifSearchInputEl.value = \"\"; resetHeatmapSelection(); activeScatterMode = \"rows\"; activeRankMode = \"rows\"; activeRankMetric = \"promiscuity_z\"; activeAnalysisTab = \"scatter\"; activeMode = requestedMode === \"quantile\" && quantileAvailable ? \"quantile\" : \"fixed\"; if (toggleFixedEl) toggleFixedEl.checked = activeMode === \"fixed\"; if (toggleQuantileEl) toggleQuantileEl.checked = activeMode === \"quantile\"; updateOrganizationControls(); renderCurrentMode(); });\n"
        "      if (orgNoneEl) orgNoneEl.addEventListener(\"click\", function() { targetOrganizationMode = \"none\"; targetOrganizationCategory = \"\"; updateOrganizationControls(); renderCurrentMode(); });\n"
        "      if (orgSafetyEl) orgSafetyEl.addEventListener(\"click\", function() { targetOrganizationMode = \"safety\"; targetOrganizationCategory = \"\"; updateOrganizationControls(); renderCurrentMode(); });\n"
        "      if (orgAdmeEl) orgAdmeEl.addEventListener(\"click\", function() { targetOrganizationMode = \"adme\"; targetOrganizationCategory = \"\"; updateOrganizationControls(); renderCurrentMode(); });\n"
        "      if (orgFamilyEl) orgFamilyEl.addEventListener(\"click\", function() { targetOrganizationMode = \"family\"; targetOrganizationCategory = \"\"; updateOrganizationControls(); renderCurrentMode(); });\n"
        "      if (orgPathwayEl) orgPathwayEl.addEventListener(\"click\", function() { targetOrganizationMode = \"pathway\"; targetOrganizationCategory = \"\"; updateOrganizationControls(); renderCurrentMode(); });\n"
        "      bindTargetOrganizationChipHandlers();\n"
        "      if (typeof bindLigandOrganizationControls === \"function\") bindLigandOrganizationControls();\n"
        "      if (typeof bindReportExtrasControls === \"function\") bindReportExtrasControls();\n"
        "      var tabButtons = document.querySelectorAll('[data-analysis-tab]');\n"
        "      for (var i = 0; i < tabButtons.length; i++) tabButtons[i].addEventListener(\"click\", function() { setAnalysisTab(this.getAttribute(\"data-analysis-tab\") || \"scatter\"); renderAnalysisPanels(); });\n"
        "      var scatterButtons = document.querySelectorAll('[data-scatter-mode]');\n"
        "      for (var j = 0; j < scatterButtons.length; j++) scatterButtons[j].addEventListener(\"click\", function() { activeScatterMode = this.getAttribute(\"data-scatter-mode\") || \"rows\"; renderAnalysisPanels(); });\n"
        "      var rankModeButtons = document.querySelectorAll('[data-rank-mode]');\n"
        "      for (var k = 0; k < rankModeButtons.length; k++) rankModeButtons[k].addEventListener(\"click\", function() { activeRankMode = this.getAttribute(\"data-rank-mode\") || \"rows\"; renderAnalysisPanels(); });\n"
        "      var rankMetricButtons = document.querySelectorAll('[data-rank-metric]');\n"
        "      for (var m = 0; m < rankMetricButtons.length; m++) rankMetricButtons[m].addEventListener(\"click\", function() { activeRankMetric = this.getAttribute(\"data-rank-metric\") || \"promiscuity_z\"; renderAnalysisPanels(); });\n"
        "    }\n"
        "    function measuredHostWidth() {\n"
        "      var rect = hostEl.getBoundingClientRect ? hostEl.getBoundingClientRect() : null;\n"
        "      var width = rect && Number.isFinite(rect.width) ? rect.width : hostEl.clientWidth;\n"
        "      return Number.isFinite(width) && width > 0 ? width : 0;\n"
        "    }\n"
        "    function computeSidebarWidth() {\n"
        "      var width = measuredHostWidth();\n"
        "      if (!width) return 160;\n"
        "      return Math.max(136, Math.min(180, Math.round(width * 0.145)));\n"
        "    }\n"
        "    function destroyHeatmapInstance() {\n"
        "      if (resizeObserver && typeof resizeObserver.disconnect === \"function\") resizeObserver.disconnect();\n"
        "      resizeObserver = null;\n"
        "      if (colLabelObserver && typeof colLabelObserver.disconnect === \"function\") colLabelObserver.disconnect();\n"
        "      colLabelObserver = null;\n"
        "      if (resizeFrame && typeof window.cancelAnimationFrame === \"function\") window.cancelAnimationFrame(resizeFrame);\n"
        "      resizeFrame = 0;\n"
        "      if (colLabelFrame && typeof window.cancelAnimationFrame === \"function\") window.cancelAnimationFrame(colLabelFrame);\n"
        "      colLabelFrame = 0;\n"
        "      if (container) container.innerHTML = \"\";\n"
        "    }\n"
        "    function applyNativeSelectionReorder() {\n"
        "      var compatEvt = new MouseEvent(\"dblclick\", { bubbles: true, cancelable: true, view: window });\n"
        "      void compatEvt;\n"
        "      return;\n"
        "    }\n"
        "    function scheduleResponsiveResize(cgm) {\n"
          "      var run = function() {\n"
          "        resizeFrame = 0;\n"
          "        if (cgm && cgm.params) cgm.params.sidebar_width = computeSidebarWidth();\n"
          "        if (cgm && typeof cgm.resize_viz === \"function\") cgm.resize_viz();\n"
          "        setTimeout(refreshInteractions, 0);\n"
          "        setTimeout(refreshInteractions, 160);\n"
          "        renderAnalysisPanels();\n"
          "      };\n"
        "      if (resizeFrame && typeof window.cancelAnimationFrame === \"function\") window.cancelAnimationFrame(resizeFrame);\n"
        "      if (typeof window.requestAnimationFrame === \"function\") {\n"
        "        resizeFrame = window.requestAnimationFrame(run);\n"
        "      } else {\n"
        "        run();\n"
        "      }\n"
        "    }\n"
        "    function bindResponsiveResize(cgm) {\n"
        "      if (typeof ResizeObserver === \"function\") {\n"
        "        resizeObserver = new ResizeObserver(function(entries) {\n"
        "          if (!entries || !entries.length) return;\n"
        "          scheduleResponsiveResize(cgm);\n"
        "        });\n"
        "        resizeObserver.observe(hostEl);\n"
        "        return;\n"
        "      }\n"
        "      window.addEventListener(\"resize\", function() { scheduleResponsiveResize(cgm); });\n"
        "    }\n"
        "    function refreshInteractions() {\n"
        "      removeDefaultSidebarLegends();\n"
        "      applyScaleMode();\n"
        "      scheduleColLabelSync();\n"
        "      renderCellValueOverlay();\n"
        "      bindDelegatedTileHandlers();\n"
        "      bindDelegatedLabelClickHandlers();\n"
        "      bindDelegatedLabelKeyHandlers();\n"
        "      renderAnalysisPanels();\n"
        "    }\n"
        "    container.addEventListener(\"mouseleave\", function() { hideHoverTip(); });\n"
        "    function renderCurrentMode() {\n"
        "      applyScaleMode();\n"
        "      applyLivePromiscuityMeta();\n"
        "      destroyHeatmapInstance();\n"
        "      var networkData = activeVizData();\n"
        "      var args = {\n"
        f"        root: \"#{container_id}\",\n"
        "        network_data: activeVizData(),\n"
        "        show_tile_tooltips: false,\n"
        "        tile_tip_callback: function() {},\n"
        "        sidebar_width: computeSidebarWidth(),\n"
        "        tile_colors: [colorRange[3] || \"#b2182b\", colorRange[0] || \"#2166ac\"],\n"
        "        input_domain: resolveInputDomain(),\n"
        "        opacity_scale: \"linear\",\n"
        "        row_label_scale: 0.88,\n"
        "        col_label_scale: 0.46,\n"
        "        matrix_update_callback: function() {\n"
        "          setTimeout(refreshInteractions, 0);\n"
        "          setTimeout(refreshInteractions, 160);\n"
        "        }\n"
        "      };\n"
        f"{row_order_js}"
        "      try { cgm = Clustergrammer(args); }\n"
        "      catch (err) {\n"
        "        var message = err && err.message ? err.message : String(err || \"unknown error\");\n"
        "        setWaitMessage(\"Heatmap failed: \" + message);\n"
        "        dumpError(\"[heatmap.debug] clustergrammer_init_failed\", err);\n"
        "        return;\n"
        "      }\n"
        "      clearWaitMessage();\n"
        "      if (cgm && cgm.params) cgm.params.sidebar_width = computeSidebarWidth();\n"
        "      if (cgm && typeof cgm.resize_viz === \"function\") cgm.resize_viz();\n"
        "      refreshInteractions();\n"
        "      renderAnalysisPanels(networkData);\n"
        "      setTimeout(refreshInteractions, 160);\n"
        "      setTimeout(scheduleColLabelSync, 500);\n"
        "      setTimeout(scheduleColLabelSync, 1200);\n"
        "      bindColLabelObserver();\n"
        "      bindResponsiveResize(cgm);\n"
        "    }\n"
        "    function initHeatmap() {\n"
        "      var initStart = nowMs();\n"
        "      debugLine(\"[heatmap.debug] Clustergrammer_type=\" + (typeof Clustergrammer));\n"
        "      var vizText = vizEl.textContent || \"\";\n"
        "      var metaText = metaEl.textContent || \"\";\n"
        "      var rowmetaText = rowmetaEl.textContent || \"\";\n"
        "      var colmetaText = colmetaEl.textContent || \"\";\n"
        "      var analysisText = analysisEl.textContent || \"\";\n"
        "      var scaleText = scaleEl.textContent || \"\";\n"
        "      if (typeof Clustergrammer === \"undefined\") {\n"
        "        setWaitMessage(\"Clustergrammer not available after asset retries.\");\n"
        "        debugLine(\"[heatmap.debug] clustergrammer_missing globals=\" + scanGlobals().join(\", \"));\n"
        "        return;\n"
        "      }\n"
        "      try { vizPayloads = JSON.parse(vizText || \"{}\"); }\n"
        "      catch (err) { setWaitMessage(\"Heatmap data parse failed.\"); dumpError(\"[heatmap.debug] viz_parse_failed\", err); return; }\n"
        "      try { cellMeta = JSON.parse(metaText || \"{}\"); }\n"
        "      catch (err) { setWaitMessage(\"Heatmap metadata parse failed.\"); dumpError(\"[heatmap.debug] meta_parse_failed\", err); return; }\n"
        "      try { baseRowMeta = JSON.parse(rowmetaText || \"{}\"); }\n"
        "      catch (err) { setWaitMessage(\"Heatmap row metadata parse failed.\"); dumpError(\"[heatmap.debug] rowmeta_parse_failed\", err); return; }\n"
        "      try { baseColMeta = JSON.parse(colmetaText || \"{}\"); }\n"
        "      catch (err) { setWaitMessage(\"Heatmap column metadata parse failed.\"); dumpError(\"[heatmap.debug] colmeta_parse_failed\", err); return; }\n"
        "      try { analysisMeta = JSON.parse(analysisText || \"{}\"); }\n"
        "      catch (err) { setWaitMessage(\"Heatmap analysis metadata parse failed.\"); dumpError(\"[heatmap.debug] analysis_parse_failed\", err); return; }\n"
        "      rowMeta = cloneJson(baseRowMeta) || {};\n"
        "      colMeta = cloneJson(baseColMeta) || {};\n"
        "      var scaleMeta = {};\n"
        "      try { scaleMeta = JSON.parse(scaleText || \"{}\"); }\n"
        "      catch (err) { setWaitMessage(\"Heatmap scale metadata parse failed.\"); dumpError(\"[heatmap.debug] scale_parse_failed\", err); return; }\n"
        "      fixedBreaks = normalizeBreaks(scaleMeta.fixed_breaks);\n"
        "      quantileBreaks = normalizeBreaks(scaleMeta.quantile_breaks);\n"
        "      chosenBreaks = normalizeBreaks(scaleMeta.chosen_breaks) || fixedBreaks;\n"
        "      requestedMode = scaleMeta.requested_scale_mode === \"quantile\" ? \"quantile\" : \"fixed\";\n"
        "      quantileAvailable = !!quantileBreaks;\n"
        "      activeMode = requestedMode === \"quantile\" && quantileAvailable ? \"quantile\" : \"fixed\";\n"
        "      activeThreshold = Math.max(0.001, Math.min(0.1, Number(analysisMeta.default_threshold_pct_rank) || 0.01));\n"
        "      activeThresholdMode = \"pct\";\n"
        "      topKDisplay = Math.max(1, Math.round(Number(analysisMeta.default_top_k) || 100));\n"
        "      targetOrganizationMode = String((analysisMeta.target_organization && analysisMeta.target_organization.default_mode) || \"none\");\n"
        "      ligandOrganizationMode = String((analysisMeta.ligand_organization && analysisMeta.ligand_organization.default_mode) || \"none\");\n"
        "      if (toggleFixedEl) toggleFixedEl.checked = activeMode === \"fixed\";\n"
        "      if (toggleQuantileEl) {\n"
        "        toggleQuantileEl.disabled = !quantileAvailable;\n"
        "        toggleQuantileEl.checked = activeMode === \"quantile\";\n"
        "      }\n"
        "      if (toggleFixedEl) {\n"
        "        toggleFixedEl.addEventListener(\"change\", function() {\n"
        "          if (!toggleFixedEl.checked) return;\n"
        "          if (activeMode === \"fixed\") return;\n"
        "          activeMode = \"fixed\";\n"
        "          renderCurrentMode();\n"
        "        });\n"
        "      }\n"
        "      if (toggleQuantileEl) {\n"
        "        toggleQuantileEl.addEventListener(\"change\", function() {\n"
        "          if (!toggleQuantileEl.checked || !quantileAvailable) return;\n"
        "          if (activeMode === \"quantile\") return;\n"
        "          activeMode = \"quantile\";\n"
        "          renderCurrentMode();\n"
        "        });\n"
        "      }\n"
        "      if (typeof hydrateReportStateFromLocation === \"function\") hydrateReportStateFromLocation();\n"
        "      bindAnalysisControls();\n"
        "      updateOrganizationControls();\n"
        "      syncControlReadout();\n"
        "      renderCurrentMode();\n"
        "      debugLine(\"[heatmap.debug] clustergrammer_init_ms=\" + (nowMs() - initStart).toFixed(1));\n"
        "    }\n"
        "    setWaitMessage(\"Loading heatmap assets...\");\n"
        "    ensureHeatmapAssets(function(ok) {\n"
        "      if (!ok) {\n"
        "        setWaitMessage(\"Clustergrammer not available after asset retries.\");\n"
        "        debugLine(\"[heatmap.assets] unresolved globals=\" + scanGlobals().join(\", \"));\n"
        "        return;\n"
        "      }\n"
        "      initHeatmap();\n"
        "    });\n"
        "  })();\n"
        "</script>"
    )
