from __future__ import annotations


def build_clustergrammer_client_script_bootstrap(
*,
container_id: str,
host_id: str,
viz_json_id: str,
meta_json_id: str,
rowmeta_json_id: str,
colmeta_json_id: str,
analysis_json_id: str,
scale_json_id: str,
scale_mode_label_id: str,
scale_breaks_label_id: str,
scale_fixed_label_id: str,
view_summary_id: str,
threshold_range_id: str,
threshold_value_id: str,
threshold_pct_id: str,
threshold_fdr_id: str,
threshold_scorch_fdr_id: str,
threshold_scorch_relaxed_fdr_id: str,
reset_button_id: str,
org_none_id: str,
org_safety_id: str,
org_adme_id: str,
org_family_id: str,
org_pathway_id: str,
safety_panel_id: str,
adme_panel_id: str,
safety_search_input_id: str,
safety_search_clear_id: str,
org_strip_id: str,
scale_legend_bar_id: str,
scale_legend_min_id: str,
scale_legend_mid_id: str,
scale_legend_mid2_id: str,
scale_legend_max_id: str,
scale_toggle_fixed_id: str,
scale_toggle_quantile_id: str,
safe_run_id: str,
ligand_prefix_json: str,
color_range_json: str,
row_order_js: str,
report_extras,
ligand_extras,
use_dendrogram: bool,
) -> str:
    return (
        "<script>\n"
        "  (function() {\n"
        f"    var container = document.getElementById(\"{container_id}\");\n"
        f"    var hostEl = document.getElementById(\"{host_id}\");\n"
        f"    var vizEl = document.getElementById(\"{viz_json_id}\");\n"
        f"    var metaEl = document.getElementById(\"{meta_json_id}\");\n"
        f"    var rowmetaEl = document.getElementById(\"{rowmeta_json_id}\");\n"
        f"    var colmetaEl = document.getElementById(\"{colmeta_json_id}\");\n"
        f"    var analysisEl = document.getElementById(\"{analysis_json_id}\");\n"
        f"    var scaleEl = document.getElementById(\"{scale_json_id}\");\n"
        f"    var modeLabelEl = document.getElementById(\"{scale_mode_label_id}\");\n"
        f"    var breaksLabelEl = document.getElementById(\"{scale_breaks_label_id}\");\n"
        f"    var fixedLabelEl = document.getElementById(\"{scale_fixed_label_id}\");\n"
        f"    var viewSummaryEl = document.getElementById(\"{view_summary_id}\");\n"
        f"    var thresholdRangeEl = document.getElementById(\"{threshold_range_id}\");\n"
        f"    var thresholdValueEl = document.getElementById(\"{threshold_value_id}\");\n"
        f"    var thresholdPctEl = document.getElementById(\"{threshold_pct_id}\");\n"
        f"    var thresholdFdrEl = document.getElementById(\"{threshold_fdr_id}\");\n"
        f"    var thresholdScorchFdrEl = document.getElementById(\"{threshold_scorch_fdr_id}\");\n"
        f"    var thresholdScorchRelaxedFdrEl = document.getElementById(\"{threshold_scorch_relaxed_fdr_id}\");\n"
        f"    var resetButtonEl = document.getElementById(\"{reset_button_id}\");\n"
        f"    var orgNoneEl = document.getElementById(\"{org_none_id}\");\n"
        f"    var orgSafetyEl = document.getElementById(\"{org_safety_id}\");\n"
        f"    var orgAdmeEl = document.getElementById(\"{org_adme_id}\");\n"
        f"    var orgFamilyEl = document.getElementById(\"{org_family_id}\");\n"
        f"    var orgPathwayEl = document.getElementById(\"{org_pathway_id}\");\n"
        f"    var safetyPanelEl = document.getElementById(\"{safety_panel_id}\");\n"
        f"    var admePanelEl = document.getElementById(\"{adme_panel_id}\");\n"
        f"    var safetySearchInputEl = document.getElementById(\"{safety_search_input_id}\");\n"
        f"    var safetySearchClearEl = document.getElementById(\"{safety_search_clear_id}\");\n"
        f"    var orgStripEl = document.getElementById(\"{org_strip_id}\");\n"
        f"    var legendBarEl = document.getElementById(\"{scale_legend_bar_id}\");\n"
        f"    var legendMinEl = document.getElementById(\"{scale_legend_min_id}\");\n"
        f"    var legendMidEl = document.getElementById(\"{scale_legend_mid_id}\");\n"
        f"    var legendMid2El = document.getElementById(\"{scale_legend_mid2_id}\");\n"
        f"    var legendMaxEl = document.getElementById(\"{scale_legend_max_id}\");\n"
        f"    var toggleFixedEl = document.getElementById(\"{scale_toggle_fixed_id}\");\n"
        f"    var toggleQuantileEl = document.getElementById(\"{scale_toggle_quantile_id}\");\n"
        f"    var assetEl = document.getElementById(\"cg-heatmap-assets-{safe_run_id}\");\n"
        "    var debugEl = document.getElementById(\"heatmap-debug-log\");\n"
        "    function debugLine(message) {\n"
        "      if (!debugEl) return;\n"
        "      debugEl.textContent += String(message) + \"\\n\";\n"
        "    }\n"
        "    function nowMs() {\n"
        "      if (window.performance && typeof window.performance.now === \"function\") return window.performance.now();\n"
        "      return Date.now();\n"
        "    }\n"
        "    function scanGlobals() {\n"
        "      var matches = [];\n"
        "      for (var key in window) {\n"
        "        if (!Object.prototype.hasOwnProperty.call(window, key)) continue;\n"
        "        if (/cluster|gram/i.test(key)) {\n"
        "          matches.push(key);\n"
        "          if (matches.length >= 20) break;\n"
        "        }\n"
        "      }\n"
        "      return matches;\n"
        "    }\n"
        "    function dumpError(label, err) {\n"
        "      var msg = String(label || \"[heatmap.error]\");\n"
        "      if (err) {\n"
        "        if (err.message) msg += \" message=\" + err.message;\n"
        "        if (err.stack) msg += \"\\n\" + err.stack;\n"
        "      }\n"
        "      debugLine(msg);\n"
        "    }\n"
        "    var prevOnError = window.onerror;\n"
        "    window.onerror = function(message, source, lineno, colno, error) {\n"
        "      var parts = [\"[heatmap.error]\", String(message || \"\"), String(source || \"\"), String(lineno || \"\"), String(colno || \"\")];\n"
        "      debugLine(parts.join(\" \"));\n"
        "      if (error && error.stack) debugLine(error.stack);\n"
        "      if (window.console && console.error) console.error(\"Heatmap error\", error || message);\n"
        "      if (typeof prevOnError === \"function\") return prevOnError(message, source, lineno, colno, error);\n"
        "      return false;\n"
        "    };\n"
        "    window.addEventListener(\"unhandledrejection\", function(evt) {\n"
        "      var reason = evt && evt.reason ? evt.reason : \"unknown\";\n"
        "      debugLine(\"[heatmap.unhandledrejection] \" + String(reason));\n"
        "      if (reason && reason.stack) debugLine(reason.stack);\n"
        "      if (window.console && console.error) console.error(\"Heatmap unhandled rejection\", reason);\n"
        "    });\n"
        "    if (!container || !hostEl || !vizEl || !metaEl || !rowmetaEl || !colmetaEl || !analysisEl || !scaleEl) {\n"
        "      debugLine(\"[heatmap.debug] missing_elements container=\" + !!container + \" host=\" + !!hostEl + \" viz=\" + !!vizEl + \" meta=\" + !!metaEl + \" rowmeta=\" + !!rowmetaEl + \" colmeta=\" + !!colmetaEl + \" analysis=\" + !!analysisEl + \" scale=\" + !!scaleEl);\n"
        "      return;\n"
        "    }\n"
        f"    var ligandPrefix = {ligand_prefix_json};\n"
        "    if (ligandPrefix && ligandPrefix.slice(-1) !== \"/\") ligandPrefix += \"/\";\n"
        f"    var colorRange = {color_range_json};\n"
        "    var cellValueMinSide = 18;\n"
        "    function escapeHtml(value) {\n"
        "      var text = String(value == null ? \"\" : value);\n"
        "      return text.replace(/[&<>\\\"]/g, function(ch) {\n"
        "        return {\"&\": \"&amp;\", \"<\": \"&lt;\", \">\": \"&gt;\", \"\\\"\": \"&quot;\"}[ch] || ch;\n"
        "      });\n"
        "    }\n"
        "    function setWaitMessage(message) {\n"
        "      if (!container) return;\n"
        "      var text = message || \"Heatmap failed to render.\";\n"
        "      var wait = container.querySelector('.wait_message');\n"
        "      if (wait) {\n"
        "        wait.textContent = text;\n"
        "        return;\n"
        "      }\n"
        "      var div = document.createElement(\"div\");\n"
        "      div.className = \"wait_message\";\n"
        "      div.textContent = text;\n"
        "      container.appendChild(div);\n"
        "    }\n"
        "    function clearWaitMessage() {\n"
        "      if (!container) return;\n"
        "      var wait = container.querySelector('.wait_message');\n"
        "      if (!wait) return;\n"
        "      if (wait.remove) wait.remove();\n"
        "      else if (wait.parentNode) wait.parentNode.removeChild(wait);\n"
        "    }\n"
        "    var assetMeta = {};\n"
        "    try { assetMeta = JSON.parse((assetEl && assetEl.textContent) || \"{}\"); }\n"
        "    catch (err) { dumpError(\"[heatmap.assets] asset_meta_parse_failed\", err); }\n"
        "    function assetCandidates(name) {\n"
        "      var urls = assetMeta && assetMeta.asset_urls ? assetMeta.asset_urls[name] : null;\n"
        "      return Array.isArray(urls) ? urls.filter(Boolean) : [];\n"
        "    }\n"
        "    function hasScriptTag(url) {\n"
        "      return !!document.querySelector('script[src=\"' + String(url).replace(/\"/g, '\\\\\"') + '\"]');\n"
        "    }\n"
        "    function hasStylesheet(url) {\n"
        "      return !!document.querySelector('link[rel=\"stylesheet\"][href=\"' + String(url).replace(/\"/g, '\\\\\"') + '\"]');\n"
        "    }\n"
        "    function loadScriptCandidate(url, callback) {\n"
        "      if (!url) { callback(false); return; }\n"
        "      if (hasScriptTag(url)) { callback(true); return; }\n"
        "      var el = document.createElement(\"script\");\n"
        "      el.src = url;\n"
        "      el.async = false;\n"
        "      el.onload = function() { callback(true); };\n"
        "      el.onerror = function() { callback(false); };\n"
        "      (document.head || document.body || document.documentElement).appendChild(el);\n"
        "    }\n"
        "    function loadStyleCandidate(url, callback) {\n"
        "      if (!url) { callback(false); return; }\n"
        "      if (hasStylesheet(url)) { callback(true); return; }\n"
        "      var el = document.createElement(\"link\");\n"
        "      el.rel = \"stylesheet\";\n"
        "      el.href = url;\n"
        "      el.onload = function() { callback(true); };\n"
        "      el.onerror = function() { callback(false); };\n"
        "      (document.head || document.body || document.documentElement).appendChild(el);\n"
        "    }\n"
        "    function loadCandidates(urls, loader, callback) {\n"
        "      if (!urls || !urls.length) { callback(false, null); return; }\n"
        "      var index = 0;\n"
        "      function tryNext() {\n"
        "        if (index >= urls.length) { callback(false, null); return; }\n"
        "        var url = urls[index++];\n"
        "        loader(url, function(ok) {\n"
        "          if (ok) { callback(true, url); return; }\n"
        "          debugLine(\"[heatmap.assets] failed \" + url);\n"
        "          tryNext();\n"
        "        });\n"
        "      }\n"
        "      tryNext();\n"
        "    }\n"
        "    function ensureAsset(check, name, loader, callback) {\n"
        "      if (check()) { callback(true); return; }\n"
        "      var urls = assetCandidates(name);\n"
        "      if (!urls.length) { callback(false); return; }\n"
        "      debugLine(\"[heatmap.assets] loading \" + name + \" candidates=\" + urls.join(\", \"));\n"
        "      loadCandidates(urls, loader, function(ok, loadedUrl) {\n"
        "        if (ok && loadedUrl) debugLine(\"[heatmap.assets] loaded \" + name + \" from \" + loadedUrl);\n"
        "        callback(check());\n"
        "      });\n"
        "    }\n"
        "    function ensureHeatmapAssets(done) {\n"
        "      if (assetMeta && assetMeta.mode) debugLine(\"[heatmap.assets] mode=\" + assetMeta.mode);\n"
        "      if (assetMeta && Array.isArray(assetMeta.notices)) {\n"
        "        for (var noticeIdx = 0; noticeIdx < assetMeta.notices.length; noticeIdx++) debugLine(\"[heatmap.assets] notice=\" + assetMeta.notices[noticeIdx]);\n"
        "      }\n"
        "      ensureAsset(function() { return true; }, \"bootstrap_css\", loadStyleCandidate, function() {\n"
        "        ensureAsset(function() { return true; }, \"font_awesome_css\", loadStyleCandidate, function() {\n"
        "          ensureAsset(function() { return true; }, \"custom_css\", loadStyleCandidate, function() {\n"
        "            ensureAsset(function() { return typeof d3 !== \"undefined\"; }, \"d3\", loadScriptCandidate, function(d3Ok) {\n"
        "              ensureAsset(function() { return !!(window.jQuery || window.$); }, \"jquery\", loadScriptCandidate, function(jqOk) {\n"
        "                ensureAsset(function() { return typeof _ !== \"undefined\"; }, \"underscore\", loadScriptCandidate, function(underscoreOk) {\n"
        "                  ensureAsset(function() { return !!(window.jQuery && window.jQuery.fn && window.jQuery.fn.modal); }, \"bootstrap_js\", loadScriptCandidate, function() {\n"
        "                    ensureAsset(function() { return typeof Clustergrammer !== \"undefined\"; }, \"clustergrammer_js\", loadScriptCandidate, function(clustergrammerOk) {\n"
        "                      done(!!(d3Ok && jqOk && underscoreOk && clustergrammerOk));\n"
        "                    });\n"
        "                  });\n"
        "                });\n"
        "              });\n"
        "            });\n"
        "          });\n"
        "        });\n"
        "      });\n"
        "    }\n"
        "    function asNumber(value) {\n"
        "      var parsed = Number(value);\n"
        "      return Number.isFinite(parsed) ? parsed : null;\n"
        "    }\n"
        "    function normalizeBreaks(raw) {\n"
        "      if (!raw || typeof raw !== \"object\") return null;\n"
        "      var b = {\n"
        "        scale_min: asNumber(raw.scale_min),\n"
        "        scale_mid: asNumber(raw.scale_mid),\n"
        "        scale_mid2: asNumber(raw.scale_mid2),\n"
        "        scale_max: asNumber(raw.scale_max)\n"
        "      };\n"
        "      if (b.scale_min == null || b.scale_mid == null || b.scale_mid2 == null || b.scale_max == null) return null;\n"
        "      if (!(b.scale_min < b.scale_mid && b.scale_mid < b.scale_mid2 && b.scale_mid2 < b.scale_max)) return null;\n"
        "      return b;\n"
        "    }\n"
        "    function modeLabelText(mode) {\n"
        "      if (mode === \"quantile\") return \"Scale mode: QUANTILE (within-run; colors are relative)\";\n"
        "      return \"Scale mode: FIXED (absolute)\";\n"
        "    }\n"
        "    function breaksLineText(breaks) {\n"
        "      if (!breaks) return \"Breaks used: unavailable\";\n"
        "      return \"Breaks used: min=\" + breaks.scale_min.toPrecision(6)\n"
        "        + \", mid=\" + breaks.scale_mid.toPrecision(6)\n"
        "        + \", mid2=\" + breaks.scale_mid2.toPrecision(6)\n"
        "        + \", max=\" + breaks.scale_max.toPrecision(6);\n"
        "    }\n"
        "    function fixedReferenceText(mode, fixedBreaks) {\n"
        "      if (mode !== \"quantile\" || !fixedBreaks) return \"\";\n"
        "      return \"Fixed reference breaks: min=\" + fixedBreaks.scale_min.toPrecision(6)\n"
        "        + \", mid=\" + fixedBreaks.scale_mid.toPrecision(6)\n"
        "        + \", mid2=\" + fixedBreaks.scale_mid2.toPrecision(6)\n"
        "        + \", max=\" + fixedBreaks.scale_max.toPrecision(6);\n"
        "    }\n"
        "    var fixedBreaks = null;\n"
        "    var quantileBreaks = null;\n"
        "    var chosenBreaks = null;\n"
        "    var requestedMode = \"fixed\";\n"
        "    var quantileAvailable = false;\n"
        "    var activeMode = \"fixed\";\n"
        "    var activeBreaks = null;\n"
        "    var vizPayloads = {};\n"
        "    var cellMeta = {};\n"
        "    var baseRowMeta = {};\n"
        "    var baseColMeta = {};\n"
        "    var rowMeta = {};\n"
        "    var colMeta = {};\n"
        "    var analysisMeta = {};\n"
        "    var currentAnalysis = null;\n"
        "    var activeThreshold = 0.01;\n"
        "    var activeThresholdMode = \"pct\";\n"
        "    var topKDisplay = 100;\n"
        "    var activeAnalysisTab = \"scatter\";\n"
        "    var activeScatterMode = \"rows\";\n"
        "    var activeRankMode = \"rows\";\n"
        "    var activeRankMetric = \"promiscuity_z\";\n"
        "    var targetOrganizationMode = \"none\";\n"
        "    var targetOrganizationCategory = \"\";\n"
        "    var activeSafetySearch = \"\";\n"
        "    var selectedPdb = \"\";\n"
        "    var selectedColLabel = \"\";\n"
        "    var selectedLigand = \"\";\n"
        "    var cgm = null;\n"
        "    var resizeObserver = null;\n"
        "    var colLabelObserver = null;\n"
        "    var resizeFrame = 0;\n"
        "    var colLabelFrame = 0;\n"
        f"{ligand_extras.script_block}\n"
        "    function cloneJson(value) {\n"
        "      if (value == null) return value;\n"
        "      return JSON.parse(JSON.stringify(value));\n"
        "    }\n"
        "    function formatBreakValue(value) {\n"
        "      if (value == null || !Number.isFinite(value)) return \"\";\n"
        "      return Number(value).toPrecision(6);\n"
        "    }\n"
        "    function formatMetric(value, digits) {\n"
        "      if (value == null || !Number.isFinite(value)) return \"0\";\n"
        "      return Number(value).toFixed(digits == null ? 6 : digits).replace(/(?:\\.0+|(?:(\\.[0-9]*?)0+))$/, \"$1\");\n"
        "    }\n"
        "    function formatPercent(value, digits) {\n"
        "      if (value == null || !Number.isFinite(value)) return \"0%\";\n"
        "      return (Number(value) * 100).toFixed(digits == null ? 2 : digits) + \"%\";\n"
        "    }\n"
        "    function thresholdModeLabel(mode) {\n"
        "      if (mode === \"fdr\") return \"FDR q\";\n"
        "      if (mode === \"scorch_fdr\") return \"SCORCH conditional q +1\";\n"
        "      if (mode === \"scorch_fdr_relaxed\") return \"SCORCH conditional q relaxed\";\n"
        "      return \"pct_rank\";\n"
        "    }\n"
        "    function thresholdMetricValue(meta) {\n"
        "      if (!meta) return null;\n"
        "      if (activeThresholdMode === \"fdr\") return asNumber(meta.fdr_q_target);\n"
        "      if (activeThresholdMode === \"scorch_fdr\") {\n"
        "        var plus1 = asNumber(meta.scorch_fdr_decoy_competition_q_plus1);\n"
        "        return plus1 == null ? asNumber(meta.scorch_fdr_decoy_competition_q) : plus1;\n"
        "      }\n"
        "      if (activeThresholdMode === \"scorch_fdr_relaxed\") return asNumber(meta.scorch_fdr_decoy_competition_q);\n"
        "      return asNumber(meta.pct_rank);\n"
        "    }\n"
        "    function thresholdDescriptor() {\n"
        "      var suffix = activeThresholdMode === \"pct\" ? formatPercent(activeThreshold, 1) : formatMetric(activeThreshold, 3);\n"
        "      return thresholdModeLabel(activeThresholdMode) + \" <= \" + suffix;\n"
        "    }\n"
        "    function updateThresholdModeButtons() {\n"
        "      if (thresholdPctEl) thresholdPctEl.classList.toggle(\"is-active\", activeThresholdMode === \"pct\");\n"
        "      if (thresholdFdrEl) thresholdFdrEl.classList.toggle(\"is-active\", activeThresholdMode === \"fdr\");\n"
        "      if (thresholdScorchFdrEl) thresholdScorchFdrEl.classList.toggle(\"is-active\", activeThresholdMode === \"scorch_fdr\");\n"
        "      if (thresholdScorchRelaxedFdrEl) thresholdScorchRelaxedFdrEl.classList.toggle(\"is-active\", activeThresholdMode === \"scorch_fdr_relaxed\");\n"
        "    }\n"
        "    function entityLabel(mode) {\n"
        "      return mode === \"cols\" ? \"Targets\" : \"Ligands\";\n"
        "    }\n"
        "    function metricLabel(metric) {\n"
        "      if (metric === \"significant_hits\") return \"Significant hit count\";\n"
        "      if (metric === \"hit_fraction\") return \"Significant hit fraction (%)\";\n"
        "      if (metric === \"entropy\") return \"Entropy\";\n"
        "      return \"Promiscuity z-score\";\n"
        "    }\n"
        "    function organizationModeLabel(mode) {\n"
        "      if (mode === \"safety\") return \"Safety\";\n"
        "      if (mode === \"adme\") return \"ADME\";\n"
        "      if (mode === \"family\") return \"Protein family\";\n"
        "      if (mode === \"pathway\") return \"Pathway\";\n"
        "      return \"None\";\n"
        "    }\n"
        "    function formatMetricValue(metric, value) {\n"
        "      if (metric === \"hit_fraction\") return formatPercent(value, 2);\n"
        "      if (metric === \"significant_hits\") return String(Math.round(Number(value || 0)));\n"
        "      return formatMetric(value, 6);\n"
        "    }\n"
        "    function updateCustomLegend() {\n"
        "      if (!legendBarEl || !activeBreaks) return;\n"
        "      if (Array.isArray(colorRange) && colorRange.length >= 4) {\n"
        "        legendBarEl.style.background = \"linear-gradient(180deg, \" + colorRange[3] + \" 0%, \" + colorRange[2] + \" 33.333%, \" + colorRange[1] + \" 66.667%, \" + colorRange[0] + \" 100%)\";\n"
        "      }\n"
        "      if (legendMinEl) legendMinEl.textContent = \"min=\" + formatBreakValue(activeBreaks.scale_min);\n"
        "      if (legendMidEl) legendMidEl.textContent = \"mid=\" + formatBreakValue(activeBreaks.scale_mid);\n"
        "      if (legendMid2El) legendMid2El.textContent = \"mid2=\" + formatBreakValue(activeBreaks.scale_mid2);\n"
        "      if (legendMaxEl) legendMaxEl.textContent = \"max=\" + formatBreakValue(activeBreaks.scale_max);\n"
        "    }\n"
        "    function updateScaleBanner() {\n"
        "      if (modeLabelEl) modeLabelEl.textContent = modeLabelText(activeMode);\n"
        "      if (breaksLabelEl) breaksLabelEl.textContent = breaksLineText(activeBreaks);\n"
        "      if (fixedLabelEl) fixedLabelEl.textContent = fixedReferenceText(activeMode, fixedBreaks);\n"
        "      updateCustomLegend();\n"
        "    }\n"
        "    function resolveActiveBreaks() {\n"
        "      if (activeMode === \"quantile\") return quantileBreaks || chosenBreaks || fixedBreaks;\n"
        "      return fixedBreaks || chosenBreaks;\n"
        "    }\n"
        "    function applyScaleMode() {\n"
        "      activeBreaks = resolveActiveBreaks();\n"
        "      updateScaleBanner();\n"
        "    }\n"
        "    function hasMetaValue(meta, key) {\n"
        "      return !!(meta && Object.prototype.hasOwnProperty.call(meta, key) && meta[key] !== \"\");\n"
        "    }\n"
        "    function activeValueText(meta) {\n"
        "      if (!meta) return \"\";\n"
        "      if (activeMode === \"quantile\" && hasMetaValue(meta, \"z_selected_quantile\")) return meta.z_selected_quantile;\n"
        "      if (activeMode === \"fixed\" && hasMetaValue(meta, \"z_selected_fixed\")) return meta.z_selected_fixed;\n"
        "      if (hasMetaValue(meta, \"z_selected\")) return meta.z_selected;\n"
        "      return meta.z_selected || \"\";\n"
        "    }\n"
        "    function activeValueNumber(meta) {\n"
        "      return asNumber(activeValueText(meta));\n"
        "    }\n"
        "    function rawScoreValue(meta) {\n"
        "      if (!meta) return null;\n"
        "      return asNumber(meta.z_selected_raw != null && meta.z_selected_raw !== \"\" ? meta.z_selected_raw : meta.z_selected);\n"
        "    }\n"
        "    function targetShortName(colName, meta) {\n"
        "      if (meta && meta.target_raw) {\n"
        "        var token = String(meta.target_raw).split(\"|\")[0] || \"\";\n"
        "        if (token) return token;\n"
        "      }\n"
        "      var raw = String(colName || \"\");\n"
        "      return raw.split(\"\\n\")[0] || raw;\n"
        "    }\n"
        "    function cgKey(value) {\n"
        "      return String(value == null ? \"\" : value).replace(/_/g, \" \");\n"
        "    }\n"
        "    function colMetaKey(value) {\n"
        "      return cgKey(value);\n"
        "    }\n"
        "    function lookupColLabelMeta(label) {\n"
        "      var key = colMetaKey(label);\n"
        "      var meta = colMeta[key] || null;\n"
        "      if (meta) return meta;\n"
        "      var pieces = String(label || \"\").split(\"\\n\");\n"
        "      var pdb = (pieces[0] || \"\").trim();\n"
        "      var targetName = (pieces[1] || pdb).trim();\n"
        "      var variantPh = (pieces[2] || \"\").trim();\n"
        "      return { pdb: pdb, target_name: targetName, variant_ph: variantPh };\n"
        "    }\n"
        "    function lookupRowLabelMeta(label) {\n"
        "      var key = cgKey(label);\n"
        "      var meta = rowMeta[key] || null;\n"
        "      if (meta) return meta;\n"
        "      return { ligand: key };\n"
        "    }\n"
        "    function targetOrganizationBlocks(mode) {\n"
        "      var meta = analysisMeta && analysisMeta.target_organization ? analysisMeta.target_organization : {};\n"
        "      if (mode === \"safety\") return Array.isArray(meta.safety_blocks) ? meta.safety_blocks : [];\n"
        "      if (mode === \"adme\") return Array.isArray(meta.adme_blocks) ? meta.adme_blocks : [];\n"
        "      if (mode === \"family\") return Array.isArray(meta.family_blocks) ? meta.family_blocks : [];\n"
        "      if (mode === \"pathway\") return Array.isArray(meta.pathway_blocks) ? meta.pathway_blocks : [];\n"
        "      return [];\n"
        "    }\n"
        "    function targetOrganizationValue(colName, mode) {\n"
        "      var meta = lookupColLabelMeta(colName);\n"
        "      if (mode === \"safety\") return String(meta.primary_display_safety || \"Unassigned\");\n"
        "      if (mode === \"adme\") return String(meta.adme_category || \"Non-ADME / Unassigned\");\n"
        "      if (mode === \"family\") return String(meta.protein_family || \"Unassigned\");\n"
        "      if (mode === \"pathway\") return String(meta.primary_display_pathway || \"Unassigned\");\n"
        "      return \"\";\n"
        "    }\n"
        "    function organizationColorMap(mode) {\n"
        "      var palette = [\"#0072B2\", \"#D55E00\", \"#009E73\", \"#CC79A7\", \"#E69F00\", \"#56B4E9\", \"#117733\", \"#332288\", \"#44AA99\", \"#AA4499\"];\n"
        "      var blocks = targetOrganizationBlocks(mode);\n"
        "      var out = Object.create(null);\n"
        "      for (var i = 0; i < blocks.length; i++) {\n"
        "        var key = String(blocks[i] && blocks[i].key || \"\");\n"
        "        out[key] = palette[i % palette.length];\n"
        "      }\n"
        "      return out;\n"
        "    }\n"
        "    function organizationColorForValue(value) {\n"
        "      if (targetOrganizationMode === \"none\") return \"\";\n"
        "      var colors = organizationColorMap(targetOrganizationMode);\n"
        "      return String(colors[String(value || \"\")] || \"#5d6f5f\");\n"
        "    }\n"
        "    function safetySearchText() {\n"
        "      return String(activeSafetySearch || \"\").trim().toLowerCase();\n"
        "    }\n"
        "    function flattenSafetySearchValues(value, out, depth) {\n"
        "      out = out || [];\n"
        "      depth = depth || 0;\n"
        "      if (value == null || depth > 4) return out;\n"
        "      if (Array.isArray(value)) {\n"
        "        for (var i = 0; i < value.length; i++) flattenSafetySearchValues(value[i], out, depth + 1);\n"
        "        return out;\n"
        "      }\n"
        "      if (typeof value === \"object\") {\n"
        "        Object.keys(value).forEach(function(key) {\n"
        "          if (key === \"metadata_json\") return;\n"
        "          flattenSafetySearchValues(value[key], out, depth + 1);\n"
        "        });\n"
        "        return out;\n"
        "      }\n"
        "      out.push(String(value));\n"
        "      return out;\n"
        "    }\n"
        "    function safetySearchMetaFields(meta) {\n"
        "      if (!meta) return [];\n"
        "      return flattenSafetySearchValues(meta, [], 0);\n"
        "    }\n"
        "    function targetMatchesSafetySearch(meta) {\n"
        "      var query = safetySearchText();\n"
        "      if (!query) return false;\n"
        "      var haystack = safetySearchMetaFields(meta).map(function(value) { return String(value || \"\").toLowerCase(); });\n"
        "      for (var i = 0; i < haystack.length; i++) {\n"
        "        if (haystack[i] && haystack[i].indexOf(query) !== -1) return true;\n"
        "      }\n"
        "      return false;\n"
        "    }\n"
        "    function matchedSafetyPrimaryKeys() {\n"
        "      var out = Object.create(null);\n"
        "      var query = safetySearchText();\n"
        "      if (!query) return out;\n"
        "      var names = allColNames();\n"
        "      for (var i = 0; i < names.length; i++) {\n"
        "        var meta = lookupColLabelMeta(names[i]);\n"
        "        if (!targetMatchesSafetySearch(meta)) continue;\n"
        "        var key = String(meta.primary_display_safety || \"Unassigned\");\n"
        "        out[key] = true;\n"
        "      }\n"
        "      return out;\n"
        "    }\n"
        "    function organizeColumnsByMode(colNames) {\n"
        "      if (targetOrganizationMode === \"none\") return colNames.slice();\n"
        "      var blocks = targetOrganizationBlocks(targetOrganizationMode);\n"
        "      var blockOrder = Object.create(null);\n"
        "      for (var i = 0; i < blocks.length; i++) blockOrder[String(blocks[i] && blocks[i].key || \"\")] = i;\n"
        "      var activeCategory = String(targetOrganizationCategory || \"\");\n"
        "      var tieOrder = stableTieOrder(colNames);\n"
        "      return colNames.slice().sort(function(a, b) {\n"
        "        var aKey = targetOrganizationValue(a, targetOrganizationMode);\n"
        "        var bKey = targetOrganizationValue(b, targetOrganizationMode);\n"
        "        if (activeCategory) {\n"
        "          var aCat = aKey === activeCategory ? 0 : 1;\n"
        "          var bCat = bKey === activeCategory ? 0 : 1;\n"
        "          if (aCat !== bCat) return aCat - bCat;\n"
        "        }\n"
        "        var aRank = Object.prototype.hasOwnProperty.call(blockOrder, aKey) ? blockOrder[aKey] : 99999;\n"
        "        var bRank = Object.prototype.hasOwnProperty.call(blockOrder, bKey) ? blockOrder[bKey] : 99999;\n"
        "        if (aRank !== bRank) return aRank - bRank;\n"
        "        if (aKey !== bKey) return aKey < bKey ? -1 : 1;\n"
        "        return Number(tieOrder[a] || 0) - Number(tieOrder[b] || 0);\n"
        "      });\n"
        "    }\n"
        "    function updateOrganizationControls() {\n"
        "      if (orgNoneEl) orgNoneEl.classList.toggle(\"is-active\", targetOrganizationMode === \"none\");\n"
        "      if (orgSafetyEl) orgSafetyEl.classList.toggle(\"is-active\", targetOrganizationMode === \"safety\");\n"
        "      if (orgAdmeEl) orgAdmeEl.classList.toggle(\"is-active\", targetOrganizationMode === \"adme\");\n"
        "      if (orgFamilyEl) orgFamilyEl.classList.toggle(\"is-active\", targetOrganizationMode === \"family\");\n"
        "      if (orgPathwayEl) orgPathwayEl.classList.toggle(\"is-active\", targetOrganizationMode === \"pathway\");\n"
        "      renderAnnotationPanels();\n"
        "      if (typeof updateLigandOrganizationControls === \"function\") updateLigandOrganizationControls();\n"
        "    }\n"
        "    function activateTargetOrganizationCategory(mode, category) {\n"
        "      var resolvedMode = [\"safety\", \"adme\", \"family\", \"pathway\"].indexOf(String(mode || \"\")) >= 0 ? String(mode) : \"none\";\n"
        "      var resolvedCategory = String(category || \"\").trim();\n"
        "      if (resolvedMode === \"none\") {\n"
        "        targetOrganizationMode = \"none\";\n"
        "        targetOrganizationCategory = \"\";\n"
        "      } else if (targetOrganizationMode === resolvedMode && targetOrganizationCategory === resolvedCategory) {\n"
        "        targetOrganizationCategory = \"\";\n"
        "      } else {\n"
        "        targetOrganizationMode = resolvedMode;\n"
        "        targetOrganizationCategory = resolvedCategory;\n"
        "      }\n"
        "      resetHeatmapSelection();\n"
        "      updateOrganizationControls();\n"
        "      renderCurrentMode();\n"
        "    }\n"
        "    function bindTargetOrganizationChipHandlers() {\n"
        "      if (!container || container.getAttribute(\"data-cg-target-chip-bind\") === \"1\") return;\n"
        "      container.setAttribute(\"data-cg-target-chip-bind\", \"1\");\n"
        "      var root = document.body;\n"
        "      root.addEventListener(\"click\", function(evt) {\n"
        "        var target = evt && evt.target ? evt.target : null;\n"
        "        if (!target || typeof target.closest !== \"function\") return;\n"
        "        var chip = target.closest('[data-org-kind=\"target\"][data-org-mode][data-org-category]');\n"
        "        if (!chip) return;\n"
        "        evt.preventDefault();\n"
        "        evt.stopPropagation();\n"
        "        activateTargetOrganizationCategory(String(chip.getAttribute(\"data-org-mode\") || \"\"), String(chip.getAttribute(\"data-org-category\") || \"\"));\n"
        "      }, true);\n"
        "    }\n"
        "    function renderAnnotationPanel(panelEl, title, note, blocks, activeMode, modeName) {\n"
        "      if (!panelEl) return;\n"
        "      panelEl.classList.toggle(\"is-active\", activeMode === modeName);\n"
        "      var matchedKeys = modeName === \"safety\" ? matchedSafetyPrimaryKeys() : Object.create(null);\n"
        "      var noteText = note;\n"
        "      if (modeName === \"safety\" && safetySearchText()) {\n"
        "        var matchCount = Object.keys(matchedKeys).length;\n"
        "        noteText = note + \" | search: \\\"\" + safetySearchText() + \"\\\" (\" + matchCount + \" bucket\" + (matchCount === 1 ? \"\" : \"s\") + \" matched)\";\n"
        "      }\n"
        "      var chips = blocks.map(function(block) {\n"
        "        var key = String(block.key || block.label || \"\");\n"
        "        var chipColor = organizationColorMap(modeName)[key] || \"#5d6f5f\";\n"
        "        var isSearchHit = !!matchedKeys[key];\n"
        "        var isActive = activeMode === modeName && key && key === String(targetOrganizationCategory || \"\");\n"
        "        return '<button type=\"button\" class=\"heatmap-org-chip' + (isSearchHit ? ' is-search-hit' : '') + (isActive ? ' is-active' : '') + '\" data-org-kind=\"target\" data-org-mode=\"' + escapeHtml(modeName) + '\" data-org-category=\"' + escapeHtml(key) + '\" style=\"border-color:' + chipColor + '55; box-shadow: inset 0 0 0 1px ' + chipColor + '1c;\"><span class=\"heatmap-org-chip-name\" style=\"color:' + chipColor + '\">' + escapeHtml(String(block.label || \"\")) + '</span><span class=\"heatmap-org-chip-count\">' + escapeHtml(String(block.count || 0)) + '</span></button>';\n"
        "      }).join(\"\");\n"
        "      panelEl.innerHTML = '<div class=\"heatmap-org-panel-head\"><div class=\"heatmap-org-panel-title\">' + escapeHtml(title) + '</div><div class=\"heatmap-org-panel-note\">' + escapeHtml(noteText) + '</div></div><div class=\"heatmap-org-panel-chips\">' + chips + '</div>';\n"
        "    }\n"
        "    function renderAnnotationPanels() {\n"
        "      renderAnnotationPanel(safetyPanelEl, \"Safety Buckets\", \"Biology-first grouping with AE detail on hover/search\", targetOrganizationBlocks(\"safety\"), targetOrganizationMode, \"safety\");\n"
        "      renderAnnotationPanel(admePanelEl, \"ADME Buckets\", \"Local ADME annotation library\", targetOrganizationBlocks(\"adme\"), targetOrganizationMode, \"adme\");\n"
        "    }\n"
        "    function renderOrganizationStrip(payload, visibleColIndices) {\n"
        "      if (!orgStripEl) return;\n"
        "      if (targetOrganizationMode === \"none\") {\n"
        "        orgStripEl.classList.remove(\"is-active\");\n"
        "        orgStripEl.innerHTML = \"\";\n"
        "        return;\n"
        "      }\n"
        "      var colNames = colNamesFromPayload(payload);\n"
        "      var visibleNames = visibleColIndices.map(function(idx) { return colNames[idx]; }).filter(Boolean);\n"
        "      if (!visibleNames.length) {\n"
        "        orgStripEl.classList.remove(\"is-active\");\n"
        "        orgStripEl.innerHTML = \"\";\n"
        "        return;\n"
        "      }\n"
        "      var runs = [];\n"
        "      for (var i = 0; i < visibleNames.length; i++) {\n"
        "        var name = visibleNames[i];\n"
        "        var label = targetOrganizationValue(name, targetOrganizationMode) || \"Unassigned\";\n"
        "        var last = runs.length ? runs[runs.length - 1] : null;\n"
        "        if (last && last.label === label) last.count += 1;\n"
        "        else runs.push({ label: label, count: 1 });\n"
        "      }\n"
        "      orgStripEl.classList.add(\"is-active\");\n"
        "      orgStripEl.innerHTML = runs.map(function(run) {\n"
        "        var bandColor = organizationColorForValue(run.label);\n"
        "        var background = 'linear-gradient(180deg, ' + bandColor + '22 0%, ' + bandColor + '14 100%)';\n"
        "        return '<div class=\"heatmap-org-block\" style=\"flex:' + String(Math.max(1, run.count)) + ' 1 0%; border-color:' + bandColor + '; background:' + background + '; box-shadow: inset 0 0 0 1px ' + bandColor + '26;\"><div class=\"heatmap-org-block-title\" style=\"color:' + bandColor + '\">' + escapeHtml(run.label) + '</div><div class=\"heatmap-org-block-count\">' + escapeHtml(String(run.count)) + ' target' + (run.count === 1 ? '' : 's') + '</div></div>';\n"
        "      }).join(\"\");\n"
        "    }\n"
        "    function tileKey(rowName, colName) {\n"
        "      return cgKey(rowName) + \"||\" + cgKey(colName);\n"
        "    }\n"
        "    function lookupMeta(rowName, colName) {\n"
        "      return cellMeta[tileKey(rowName, colName)];\n"
        "    }\n"
        "    function appendPromiscuityLines(lines, meta) {\n"
        "      if (!meta) return lines;\n"
        "      if (hasMetaValue(meta, \"promiscuity_z\")) lines.push(\"promiscuity_z: \" + String(meta.promiscuity_z));\n"
        "      if (hasMetaValue(meta, \"significant_hits_text\")) lines.push(\"significant_hits: \" + String(meta.significant_hits_text));\n"
        "      else if (hasMetaValue(meta, \"significant_hits\") && hasMetaValue(meta, \"partner_total\")) lines.push(\"significant_hits: \" + String(meta.significant_hits) + \" / \" + String(meta.partner_total));\n"
        "      if (hasMetaValue(meta, \"hit_fraction_pct\")) lines.push(\"hit_fraction: \" + String(meta.hit_fraction_pct));\n"
        "      else if (hasMetaValue(meta, \"hit_fraction\")) lines.push(\"hit_fraction: \" + String(meta.hit_fraction));\n"
        "      if (hasMetaValue(meta, \"entropy\")) lines.push(\"entropy: \" + String(meta.entropy));\n"
        "      if (hasMetaValue(meta, \"threshold_mode\") && hasMetaValue(meta, \"threshold_value\")) lines.push(\"threshold: \" + String(meta.threshold_mode) + \" <= \" + String(meta.threshold_value));\n"
        "      else if (hasMetaValue(meta, \"threshold_pct_rank\")) lines.push(\"threshold: pct_rank <= \" + String(meta.threshold_pct_rank));\n"
        "      return lines;\n"
        "    }\n"
        "    function appendTargetSafetyLines(lines, meta) {\n"
        "      if (!meta) return lines;\n"
        "      lines.push(\"adme: \" + String(meta.adme_category || \"Non-ADME / Unassigned\"));\n"
        "      lines.push(\"safety_primary: \" + String(meta.primary_display_safety || \"Unassigned\"));\n"
        "      if (Array.isArray(meta.secondary_safety_buckets) && meta.secondary_safety_buckets.length) lines.push(\"safety_secondary: \" + String(meta.secondary_safety_buckets.join(\"; \")));\n"
        "      if (hasMetaValue(meta, \"safety_confidence\")) lines.push(\"safety_confidence: \" + String(meta.safety_confidence));\n"
        "      if (Array.isArray(meta.safety_sources) && meta.safety_sources.length) lines.push(\"safety_sources: \" + String(meta.safety_sources.join(\"; \")));\n"
        "      if (Array.isArray(meta.direct_liability_examples) && meta.direct_liability_examples.length) lines.push(\"liability_examples: \" + String(meta.direct_liability_examples.join(\"; \"))); if (Array.isArray(meta.raw_adverse_event_examples) && meta.raw_adverse_event_examples.length) lines.push(\"adverse_event_examples: \" + String(meta.raw_adverse_event_examples.join(\"; \"))); if (Array.isArray(meta.side_effects) && meta.side_effects.length) lines.push(\"side_effects: \" + String(meta.side_effects.join(\"; \")));\n"
        "      return lines;\n"
        "    }\n"
        "    function baseVizData() {\n"
        "      if (activeMode === \"quantile\" && vizPayloads.quantile) return vizPayloads.quantile;\n"
        "      return vizPayloads.fixed || vizPayloads.quantile || {};\n"
        "    }\n"
        "    function rowNamesFromPayload(payload) {\n"
        "      var nodes = payload && Array.isArray(payload.row_nodes) ? payload.row_nodes : [];\n"
        "      return nodes.map(function(node) { return String((node && node.name) || \"\"); });\n"
        "    }\n"
        "    function colNamesFromPayload(payload) {\n"
        "      var nodes = payload && Array.isArray(payload.col_nodes) ? payload.col_nodes : [];\n"
        "      return nodes.map(function(node) { return String((node && node.name) || \"\"); });\n"
        "    }\n"
        "    function allRowNames() { return rowNamesFromPayload(baseVizData()); }\n"
        "    function allColNames() { return colNamesFromPayload(baseVizData()); }\n"
        "    function buildIndexMap(names) {\n"
        "      var out = Object.create(null);\n"
        "      for (var i = 0; i < names.length; i++) out[names[i]] = i;\n"
        "      return out;\n"
        "    }\n"
        "    function clearPdbSelection() {\n"
        "      selectedColLabel = \"\";\n"
        "      selectedPdb = \"\";\n"
        "    }\n"
        "    function clearLigandSort() {\n"
        "      selectedLigand = \"\";\n"
        "    }\n"
        "    function resetHeatmapSelection() {\n"
        "      clearPdbSelection();\n"
        "      clearLigandSort();\n"
        "    }\n"
        "    function activatePdbSelection(label, pdb) {\n"
        "      var resolvedLabel = String(label || \"\");\n"
        "      var resolvedPdb = String(pdb || \"\").trim();\n"
        "      var sameSelection = !selectedLigand && selectedColLabel === resolvedLabel;\n"
        "      if (sameSelection) {\n"
        "        resetHeatmapSelection();\n"
        "        return;\n"
        "      }\n"
        "      clearLigandSort();\n"
        "      selectedColLabel = resolvedLabel;\n"
        "      selectedPdb = resolvedPdb;\n"
        "    }\n"
        "    function activateLigandSort(label) {\n"
        "      var rowName = String(label || \"\");\n"
        "      var sameSelection = !selectedColLabel && selectedLigand === rowName;\n"
        "      if (sameSelection) {\n"
        "        resetHeatmapSelection();\n"
        "        return;\n"
        "      }\n"
        "      clearPdbSelection();\n"
        "      selectedLigand = rowName;\n"
        "    }\n"
        "    function activeInteractionMode() {\n"
        "      if (selectedColLabel) return \"pdb\";\n"
        "      if (selectedLigand) return \"ligand\";\n"
        "      return \"none\";\n"
        "    }\n"
        "    function reindexNodes(nodes) {\n"
        "      var total = nodes.length;\n"
        "      for (var i = 0; i < nodes.length; i++) {\n"
        "        var node = nodes[i];\n"
        "        if (!node || typeof node !== \"object\") continue;\n"
        "        node.clust = total - i;\n"
        "        node.ini = total - i;\n"
        "        node.rank = total - i;\n"
        "        node.rankvar = total - i;\n"
        "      }\n"
        "      return nodes;\n"
        "    }\n"
        "    function median(values) {\n"
        "      if (!values.length) return null;\n"
        "      var sorted = values.slice().sort(function(a, b) { return a - b; });\n"
        "      var mid = Math.floor(sorted.length / 2);\n"
        "      return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;\n"
        "    }\n"
        "    function robustZByName(countMap, names) {\n"
        "      if (!names.length) return {};\n"
        "      var values = names.map(function(name) { return Number(countMap[name] || 0); });\n"
        "      var med = median(values);\n"
        "      var out = {};\n"
        "      if (med == null) {\n"
        "        for (var a = 0; a < names.length; a++) out[names[a]] = 0;\n"
        "        return out;\n"
        "      }\n"
        "      var deviations = values.map(function(value) { return Math.abs(value - med); });\n"
        "      var mad = median(deviations) || 0;\n"
        "      if (mad > 0) {\n"
        "        for (var b = 0; b < names.length; b++) out[names[b]] = 0.67449 * ((Number(countMap[names[b]] || 0) - med) / mad);\n"
        "        return out;\n"
        "      }\n"
        "      var mean = values.reduce(function(sum, value) { return sum + value; }, 0) / values.length;\n"
        "      var variance = values.reduce(function(sum, value) { var delta = value - mean; return sum + delta * delta; }, 0) / values.length;\n"
        "      var std = Math.sqrt(variance);\n"
        "      for (var c = 0; c < names.length; c++) out[names[c]] = std > 0 ? (Number(countMap[names[c]] || 0) - mean) / std : 0;\n"
        "      return out;\n"
        "    }\n"
    )
