from __future__ import annotations


def build_clustergrammer_client_script_interactions(
*,
container_id: str,
host_id: str,
viz_json_id: str,
meta_json_id: str,
rowmeta_json_id: str,
colmeta_json_id: str,
analysis_json_id: str,
scale_json_id: str,
scale_mode_label_id: str,
scale_breaks_label_id: str,
scale_fixed_label_id: str,
view_summary_id: str,
threshold_range_id: str,
threshold_value_id: str,
threshold_pct_id: str,
threshold_fdr_id: str,
threshold_scorch_fdr_id: str,
threshold_scorch_relaxed_fdr_id: str,
reset_button_id: str,
org_none_id: str,
org_safety_id: str,
org_adme_id: str,
org_family_id: str,
org_pathway_id: str,
safety_panel_id: str,
adme_panel_id: str,
safety_search_input_id: str,
safety_search_clear_id: str,
org_strip_id: str,
scale_legend_bar_id: str,
scale_legend_min_id: str,
scale_legend_mid_id: str,
scale_legend_mid2_id: str,
scale_legend_max_id: str,
scale_toggle_fixed_id: str,
scale_toggle_quantile_id: str,
safe_run_id: str,
ligand_prefix_json: str,
color_range_json: str,
row_order_js: str,
report_extras,
ligand_extras,
use_dendrogram: bool,
) -> str:
    return (
        "    function normalizedEntropy(weights) {\n"
        "      var k = weights.length;\n"
        "      if (k <= 1) return 0;\n"
        "      var positive = weights.map(function(value) { return Math.max(Number(value) || 0, 0); });\n"
        "      var total = positive.reduce(function(sum, value) { return sum + value; }, 0);\n"
        "      var probs = total > 0 ? positive.map(function(value) { return value / total; }) : positive.map(function() { return 1 / k; });\n"
        "      var entropy = 0;\n"
        "      for (var i = 0; i < probs.length; i++) if (probs[i] > 0) entropy -= probs[i] * Math.log(probs[i]);\n"
        "      return entropy / Math.log(k);\n"
        "    }\n"
        "    function metaPassesThreshold(meta) {\n"
        "      var thresholdValue = thresholdMetricValue(meta);\n"
        "      if (thresholdValue == null || thresholdValue > activeThreshold) return false;\n"
        "      var pose = String(meta && meta.pose_valid_any || \"\").trim().toLowerCase();\n"
        "      if (!pose) return true;\n"
        "      return pose === \"1\" || pose === \"true\" || pose === \"yes\" || pose === \"on\";\n"
        "    }\n"
        "    function computePromiscuityAnalysis() {\n"
        "      var rows = allRowNames();\n"
        "      var cols = allColNames();\n"
        "      var rowCounts = Object.create(null);\n"
        "      var colCounts = Object.create(null);\n"
        "      var rowWeights = Object.create(null);\n"
        "      var colWeights = Object.create(null);\n"
        "      var edges = [];\n"
        "      for (var i = 0; i < rows.length; i++) { rowCounts[rows[i]] = 0; rowWeights[rows[i]] = []; }\n"
        "      for (var j = 0; j < cols.length; j++) { colCounts[cols[j]] = 0; colWeights[cols[j]] = []; }\n"
        "      for (var key in cellMeta) {\n"
        "        if (!Object.prototype.hasOwnProperty.call(cellMeta, key)) continue;\n"
        "        var pieces = key.split(\"||\");\n"
        "        if (pieces.length < 2) continue;\n"
        "        var rowName = pieces[0];\n"
        "        var colName = pieces.slice(1).join(\"||\");\n"
        "        var meta = cellMeta[key];\n"
        "        if (!metaPassesThreshold(meta)) continue;\n"
        "        var weight = rawScoreValue(meta);\n"
        "        if (!Object.prototype.hasOwnProperty.call(rowCounts, rowName)) { rowCounts[rowName] = 0; rowWeights[rowName] = []; }\n"
        "        if (!Object.prototype.hasOwnProperty.call(colCounts, colName)) { colCounts[colName] = 0; colWeights[colName] = []; }\n"
        "        rowCounts[rowName] = Number(rowCounts[rowName] || 0) + 1;\n"
        "        colCounts[colName] = Number(colCounts[colName] || 0) + 1;\n"
        "        rowWeights[rowName].push(weight == null ? 0 : weight);\n"
        "        colWeights[colName].push(weight == null ? 0 : weight);\n"
        "        edges.push({ row: rowName, col: colName, z: weight == null ? 0 : weight, threshold_mode: activeThresholdMode, threshold_value: thresholdMetricValue(meta) || 0, pct_rank: asNumber(meta.pct_rank) || 0 });\n"
        "      }\n"
        "      var rowZ = robustZByName(rowCounts, rows);\n"
        "      var colZ = robustZByName(colCounts, cols);\n"
        "      var rowMetrics = Object.create(null);\n"
        "      var colMetrics = Object.create(null);\n"
        "      for (var r = 0; r < rows.length; r++) {\n"
        "        var rowName2 = rows[r];\n"
        "        var hitCount = Number(rowCounts[rowName2] || 0);\n"
        "        var hitFraction = cols.length ? hitCount / cols.length : 0;\n"
        "        rowMetrics[rowName2] = {\n"
        "          promiscuity_z: formatMetric(rowZ[rowName2] || 0, 6),\n"
        "          significant_hits: String(hitCount),\n"
        "          partner_total: String(cols.length),\n"
        "          significant_hits_text: String(hitCount) + \" / \" + String(cols.length),\n"
        "          hit_fraction: formatMetric(hitFraction, 6),\n"
        "          hit_fraction_pct: formatPercent(hitFraction, 2),\n"
        "          entropy: formatMetric(normalizedEntropy(rowWeights[rowName2] || []), 6),\n"
        "          threshold_pct_rank: activeThresholdMode === \"pct\" ? formatMetric(activeThreshold, 6) : \"\",\n"
        "          threshold_mode: thresholdModeLabel(activeThresholdMode),\n"
        "          threshold_value: formatMetric(activeThreshold, 6)\n"
        "        };\n"
        "      }\n"
        "      for (var c2 = 0; c2 < cols.length; c2++) {\n"
        "        var colName2 = cols[c2];\n"
        "        var colHitCount = Number(colCounts[colName2] || 0);\n"
        "        var colHitFraction = rows.length ? colHitCount / rows.length : 0;\n"
        "        colMetrics[colName2] = {\n"
        "          promiscuity_z: formatMetric(colZ[colName2] || 0, 6),\n"
        "          significant_hits: String(colHitCount),\n"
        "          partner_total: String(rows.length),\n"
        "          significant_hits_text: String(colHitCount) + \" / \" + String(rows.length),\n"
        "          hit_fraction: formatMetric(colHitFraction, 6),\n"
        "          hit_fraction_pct: formatPercent(colHitFraction, 2),\n"
        "          entropy: formatMetric(normalizedEntropy(colWeights[colName2] || []), 6),\n"
        "          threshold_pct_rank: activeThresholdMode === \"pct\" ? formatMetric(activeThreshold, 6) : \"\",\n"
        "          threshold_mode: thresholdModeLabel(activeThresholdMode),\n"
        "          threshold_value: formatMetric(activeThreshold, 6)\n"
        "        };\n"
        "      }\n"
        "      return { rowMetrics: rowMetrics, colMetrics: colMetrics, edges: edges };\n"
        "    }\n"
        "    function applyLivePromiscuityMeta() {\n"
        "      currentAnalysis = computePromiscuityAnalysis();\n"
        "      rowMeta = cloneJson(baseRowMeta) || {};\n"
        "      colMeta = cloneJson(baseColMeta) || {};\n"
        "      var rowNames = allRowNames();\n"
        "      var colNames = allColNames();\n"
        "      for (var i = 0; i < rowNames.length; i++) rowMeta[rowNames[i]] = Object.assign({}, rowMeta[rowNames[i]] || { ligand: rowNames[i] }, currentAnalysis.rowMetrics[rowNames[i]] || {});\n"
        "      for (var j = 0; j < colNames.length; j++) colMeta[colNames[j]] = Object.assign({}, colMeta[colNames[j]] || {}, currentAnalysis.colMetrics[colNames[j]] || {});\n"
        "    }\n"
        "    function defaultRankedRows() {\n"
        "      var rows = allRowNames();\n"
        "      var keep = Object.create(null);\n"
        "      for (var i = 0; i < rows.length; i++) keep[cgKey(rows[i])] = rows[i];\n"
        "      var ranked = (Array.isArray(analysisMeta.ranked_rows) ? analysisMeta.ranked_rows : rows).map(cgKey);\n"
        "      var out = ranked.filter(function(name) { return Object.prototype.hasOwnProperty.call(keep, name); }).map(function(name) { return keep[name]; });\n"
        "      for (var i = 0; i < rows.length; i++) if (out.indexOf(rows[i]) === -1) out.push(rows[i]);\n"
        "      return out;\n"
        "    }\n"
        "    function defaultVisibleRows() {\n"
        "      var ranked = defaultRankedRows();\n"
        "      var limit = Math.max(1, Math.min(topKDisplay, ranked.length));\n"
        "      return ranked.slice(0, limit);\n"
        "    }\n"
        "    function stableTieOrder(names) {\n"
        "      var order = Object.create(null);\n"
        "      for (var i = 0; i < names.length; i++) order[names[i]] = i;\n"
        "      return order;\n"
        "    }\n"
        "    function sortByCellScore(names, scorer, tieOrder) {\n"
        "      return names.slice().sort(function(a, b) {\n"
        "        var av = scorer(a);\n"
        "        var bv = scorer(b);\n"
        "        var ax = av == null ? -Infinity : av;\n"
        "        var bx = bv == null ? -Infinity : bv;\n"
        "        if (bx !== ax) return bx - ax;\n"
        "        return Number(tieOrder[a] || 0) - Number(tieOrder[b] || 0);\n"
        "      });\n"
        "    }\n"
        "    function normalizeSelectionState(payload) {\n"
        "      var rowNames = rowNamesFromPayload(payload);\n"
        "      var colNames = colNamesFromPayload(payload);\n"
        "      if (selectedLigand && rowNames.indexOf(selectedLigand) === -1) clearLigandSort();\n"
        "      if (selectedColLabel && colNames.indexOf(selectedColLabel) === -1) clearPdbSelection();\n"
        "    }\n"
        "    function derivedRowIndices(payload) {\n"
        "      var rowNames = rowNamesFromPayload(payload);\n"
        "      var rowIndexMap = buildIndexMap(rowNames);\n"
        "      var orderedNames = typeof organizeRowsByMode === \"function\" ? organizeRowsByMode(defaultVisibleRows()) : defaultVisibleRows();\n"
        "      if (selectedColLabel) {\n"
        "        if (typeof sortRowsWithinOrganization === \"function\" && ligandOrganizationMode !== \"none\") {\n"
        "          orderedNames = sortRowsWithinOrganization(defaultVisibleRows(), function(rowName) {\n"
        "            return rawScoreValue(lookupMeta(rowName, selectedColLabel));\n"
        "          }).slice(0, Math.max(1, Math.min(topKDisplay, rowNames.length)));\n"
        "        } else {\n"
        "          var tieOrder = stableTieOrder(defaultRankedRows());\n"
        "          orderedNames = sortByCellScore(defaultRankedRows(), function(rowName) {\n"
        "            return rawScoreValue(lookupMeta(rowName, selectedColLabel));\n"
        "          }, tieOrder).slice(0, Math.max(1, Math.min(topKDisplay, rowNames.length)));\n"
        "        }\n"
        "      }\n"
        "      return orderedNames.filter(function(name) { return Object.prototype.hasOwnProperty.call(rowIndexMap, name); }).map(function(name) { return rowIndexMap[name]; });\n"
        "    }\n"
        "    function derivedColIndices(payload) {\n"
        "      var colNames = colNamesFromPayload(payload);\n"
        "      var colIndexMap = buildIndexMap(colNames);\n"
        "      if (selectedColLabel) {\n"
        "        return Object.prototype.hasOwnProperty.call(colIndexMap, selectedColLabel) ? [colIndexMap[selectedColLabel]] : [];\n"
        "      }\n"
        "      var orderedNames = organizeColumnsByMode(colNames);\n"
        "      if (selectedLigand) {\n"
        "        var tieOrder = stableTieOrder(colNames);\n"
        "        orderedNames = sortByCellScore(colNames, function(colName) {\n"
        "          return rawScoreValue(lookupMeta(selectedLigand, colName));\n"
        "        }, tieOrder);\n"
        "      }\n"
        "      return orderedNames.filter(function(name) { return Object.prototype.hasOwnProperty.call(colIndexMap, name); }).map(function(name) { return colIndexMap[name]; });\n"
        "    }\n"
        "    function syncControlReadout() {\n"
        "      if (thresholdRangeEl) thresholdRangeEl.value = String(activeThreshold.toFixed(3));\n"
        "      if (thresholdValueEl) thresholdValueEl.textContent = thresholdDescriptor();\n"
        "      updateThresholdModeButtons();\n"
        "    }\n"
        "    function updateViewSummary(payload, visibleRowIndices, visibleColIndices) {\n"
        "      if (!viewSummaryEl) return;\n"
        "      if (!Array.isArray(visibleRowIndices)) visibleRowIndices = derivedRowIndices(payload);\n"
        "      if (!Array.isArray(visibleColIndices)) visibleColIndices = derivedColIndices(payload);\n"
        "      var totalCols = colNamesFromPayload(payload).length;\n"
        "      var line = \"Targets shown: \" + visibleColIndices.length + \" / \" + totalCols + \" | Threshold: \" + thresholdDescriptor();\n"
        "      if (targetOrganizationMode !== \"none\") line += \" | Target organization: \" + organizationModeLabel(targetOrganizationMode);\n"
        "      if (ligandOrganizationMode !== \"none\") line += \" | Ligand organization: \" + ligandOrganizationModeLabel(ligandOrganizationMode);\n"
        "      if (safetySearchText()) line += \" | Side-effect/AE search: \" + safetySearchText();\n"
        "      if (motifSearchText()) line += \" | Motif search: \" + motifSearchText();\n"
        "      if (activeInteractionMode() === \"pdb\" && selectedPdb) line += \" | PDB selected: \" + selectedPdb;\n"
        "      if (activeInteractionMode() === \"ligand\" && selectedLigand) line += \" | Ligand sort: \" + selectedLigand;\n"
        "      viewSummaryEl.textContent = line;\n"
        "      syncControlReadout();\n"
        "      if (typeof refreshReportExtras === \"function\") refreshReportExtras(payload, visibleRowIndices, visibleColIndices);\n"
        "    }\n"
        "    function formatDisplayNumber(value) {\n"
        "      return value == null || !Number.isFinite(value) ? \"\" : Number(value).toPrecision(6).replace(/(?:\\.0+|(?:(\\.[0-9]*?)0+))$/, \"$1\");\n"
        "    }\n"
        "    function visibleTileNumber(tile, meta) {\n"
        "      var data = tile && tile.__data__ ? tile.__data__ : {};\n"
        "      if (tile && tile.classList && tile.classList.contains(\"tile_up\")) {\n"
        "        var up = asNumber(data.value_up);\n"
        "        if (up != null) return up;\n"
        "      }\n"
        "      if (tile && tile.classList && tile.classList.contains(\"tile_dn\")) {\n"
        "        var dn = asNumber(data.value_dn);\n"
        "        if (dn != null) return dn;\n"
        "      }\n"
        "      var raw = asNumber(data.value);\n"
        "      if (raw != null) return raw;\n"
        "      return activeValueNumber(meta);\n"
        "    }\n"
        "    function buildLines(tile, rowName, colName, meta) {\n"
        "      var visibleVal = visibleTileNumber(tile, meta);\n"
        "      var displayVal = visibleVal == null ? activeValueText(meta) : formatDisplayNumber(visibleVal);\n"
        "      var targetText = targetShortName(colName, meta);\n"
        "      var lines = [\"ligand: \" + rowName, \"target: \" + targetText, \"Atlas score: \" + (displayVal || \"NA\")];\n"
        "      if (meta && meta.z_selected_raw && displayVal && meta.z_selected_raw !== displayVal) lines.push(\"Raw Atlas score: \" + meta.z_selected_raw);\n"
        "      if (meta && meta.rank) lines.push(\"rank: \" + meta.rank);\n"
        "      if (meta && meta.pct_rank) lines.push(\"pct_rank: \" + meta.pct_rank);\n"
        "      if (meta && meta.pose_invalid_reason_top) lines.push(\"pose_invalid_reason_top: \" + meta.pose_invalid_reason_top);\n"
        "      return lines;\n"
        "    }\n"
        "    function handleTileClick(tile, evt) {\n"
        "      if (!tile) return;\n"
        "      if (evt) {\n"
        "        evt.preventDefault();\n"
        "        evt.stopPropagation();\n"
        "      }\n"
        "    }\n"
        "    function isTileElement(node) {\n"
        "      return !!(node && typeof node.matches === \"function\" && node.matches(\".tile, .tile_up, .tile_dn\"));\n"
        "    }\n"
        "    function closestTile(node) {\n"
        "      if (!node) return null;\n"
        "      if (typeof node.closest === \"function\") {\n"
        "        var found = node.closest(\".tile, .tile_up, .tile_dn\");\n"
        "        if (found && container.contains(found)) return found;\n"
        "      }\n"
        "      var cur = node;\n"
        "      while (cur && cur !== container) {\n"
        "        if (isTileElement(cur)) return cur;\n"
        "        cur = cur.parentNode;\n"
        "      }\n"
        "      return null;\n"
        "    }\n"
        "    function closestLabelMatch(node, selector) {\n"
        "      var cur = node && node.nodeType === 3 ? node.parentNode : node;\n"
        "      while (cur && cur !== container) {\n"
        "        if (typeof cur.matches === \"function\" && cur.matches(selector)) return cur;\n"
        "        cur = cur.parentNode;\n"
        "      }\n"
        "      return null;\n"
        "    }\n"
        "    function closestColLabelClickTarget(node) {\n"
        "      return closestLabelMatch(node, \".col_label_text\") || closestLabelMatch(node, \"text.col_label_text\");\n"
        "    }\n"
        "    function closestRowLabelClickTarget(node) {\n"
        "      return closestLabelMatch(node, \".row_label_group\") || closestLabelMatch(node, \"text.row_label_group\");\n"
        "    }\n"
        "    var activeHoverTile = null;\n"
        "    function bindDelegatedTileHandlers() {\n"
        "      if (container.getAttribute(\"data-cg-tile-delegated\") === \"1\") return;\n"
        "      container.setAttribute(\"data-cg-tile-delegated\", \"1\");\n"
        "      container.addEventListener(\"pointermove\", function(evt) {\n"
        "        var tile = closestTile(evt.target);\n"
        "        if (!tile) {\n"
        "          if (activeHoverTile) hideHoverTip();\n"
        "          activeHoverTile = null;\n"
        "          return;\n"
        "        }\n"
        "        var d = tile.__data__ || {};\n"
        "        var rr = d.row_name || d.row || \"\";\n"
        "        var cc = d.col_name || d.col || \"\";\n"
        "        var mm = lookupMeta(rr, cc);\n"
        "        if (tile !== activeHoverTile) {\n"
        "          showHoverTip(buildLines(tile, rr, cc, mm), evt.clientX, evt.clientY);\n"
        "          activeHoverTile = tile;\n"
        "          return;\n"
        "        }\n"
        "        moveHoverTip(evt.clientX, evt.clientY);\n"
        "      });\n"
        "      container.addEventListener(\"pointerleave\", function() {\n"
        "        activeHoverTile = null;\n"
        "        hideHoverTip();\n"
        "      });\n"
        "      container.addEventListener(\"click\", function(evt) {\n"
        "        var tile = closestTile(evt.target);\n"
        "        if (!tile) return;\n"
        "        handleTileClick(tile, evt);\n"
        "      });\n"
        "    }\n"
        "    function bindDelegatedLabelClickHandlers() {\n"
        "      if (container.getAttribute(\"data-cg-label-click-delegated\") === \"1\") return;\n"
        "      container.setAttribute(\"data-cg-label-click-delegated\", \"1\");\n"
        "      container.addEventListener(\"click\", function(evt) {\n"
        "        var colNode = closestColLabelClickTarget(evt.target);\n"
        "        if (colNode) {\n"
        "          evt.preventDefault();\n"
        "          evt.stopPropagation();\n"
        "          var colTextNode = typeof colNode.querySelector === \"function\" ? (colNode.querySelector(\"text\") || colNode) : colNode;\n"
        "          var meta = lookupColLabelMeta(rawColLabel(colTextNode));\n"
        "          var pdb = String(meta.pdb || \"\").trim();\n"
        "          if (!pdb) return;\n"
        "          var rawLabel = rawColLabel(colTextNode);\n"
        "          var resolvedLabel = resolvePayloadColLabel(rawLabel);\n"
        "          activatePdbSelection(resolvedLabel, pdb);\n"
        "          hideHoverTip();\n"
        "          renderCurrentMode();\n"
        "          return;\n"
        "        }\n"
        "        var rowNode = closestRowLabelClickTarget(evt.target);\n"
        "        if (!rowNode) return;\n"
        "        evt.preventDefault();\n"
        "        evt.stopPropagation();\n"
        "        var rowName = rawRowGroupLabel(rowNode);\n"
        "        if (!rowName) return;\n"
        "        activateLigandSort(rowName);\n"
        "        hideHoverTip();\n"
        "        renderCurrentMode();\n"
        "      }, true);\n"
        "    }\n"
        "    function bindDelegatedLabelKeyHandlers() {\n"
        "      if (container.getAttribute(\"data-cg-label-key-delegated\") === \"1\") return;\n"
        "      container.setAttribute(\"data-cg-label-key-delegated\", \"1\");\n"
        "      container.addEventListener(\"keydown\", function(evt) {\n"
        "        if (!evt || (evt.key !== \"Enter\" && evt.key !== \" \")) return;\n"
        "        var colNode = closestColLabelClickTarget(evt.target);\n"
        "        if (colNode) {\n"
        "          evt.preventDefault();\n"
        "          evt.stopPropagation();\n"
        "          var colTextNode = typeof colNode.querySelector === \"function\" ? (colNode.querySelector(\"text\") || colNode) : colNode;\n"
        "          var meta = lookupColLabelMeta(rawColLabel(colTextNode));\n"
        "          var pdb = String(meta.pdb || \"\").trim();\n"
        "          if (!pdb) return;\n"
        "          var rawLabel = rawColLabel(colTextNode);\n"
        "          var resolvedLabel = resolvePayloadColLabel(rawLabel);\n"
        "          activatePdbSelection(resolvedLabel, pdb);\n"
        "          hideHoverTip(true);\n"
        "          renderCurrentMode();\n"
        "          return;\n"
        "        }\n"
        "        var rowNode = closestRowLabelClickTarget(evt.target);\n"
        "        if (!rowNode) return;\n"
        "        evt.preventDefault();\n"
        "        evt.stopPropagation();\n"
        "        var rowName = rawRowGroupLabel(rowNode);\n"
        "        if (!rowName) return;\n"
        "        activateLigandSort(rowName);\n"
        "        hideHoverTip(true);\n"
        "        renderCurrentMode();\n"
        "      }, true);\n"
        "      container.addEventListener(\"keydown\", function(evt) {\n"
        "        if (!evt || evt.key !== \"Escape\") return;\n"
        "        hideHoverTip(true);\n"
        "      }, true);\n"
        "    }\n"
        "    function ensureHoverTip() {\n"
        "      var tip = document.getElementById(\"cg-hover-tip\");\n"
        "      if (tip) return tip;\n"
        "      tip = document.createElement(\"div\");\n"
        "      tip.id = \"cg-hover-tip\";\n"
        "      tip.className = \"cg-hover-tip\";\n"
        "      tip.style.display = \"none\";\n"
        "      document.body.appendChild(tip);\n"
        "      return tip;\n"
        "    }\n"
        "    var hoverAnchorX = null;\n"
        "    var hoverAnchorY = null;\n"
        "    var hoverHideTimer = 0;\n"
        "    function clearHoverHideTimer() {\n"
        "      if (hoverHideTimer && typeof window.clearTimeout === \"function\") window.clearTimeout(hoverHideTimer);\n"
        "      hoverHideTimer = 0;\n"
        "    }\n"
        "    function tooltipLineHtml(line) {\n"
        "      var text = String(line || \"\");\n"
        "      var idx = text.indexOf(\":\");\n"
        "      if (idx <= 0) return '<div class=\"tip-row\"><span class=\"tip-val\">' + escapeHtml(text) + '</span></div>';\n"
        "      var key = text.slice(0, idx + 1);\n"
        "      var value = text.slice(idx + 1).trim();\n"
        "      return '<div class=\"tip-row\"><span class=\"tip-key\">' + escapeHtml(key) + '</span> <span class=\"tip-val\">' + escapeHtml(value) + '</span></div>';\n"
        "    }\n"
        "    function moveHoverTip(x, y) {\n"
        "      var tip = ensureHoverTip();\n"
        "      if (!tip || tip.style.display === \"none\") return;\n"
        "      if (x != null && Number.isFinite(x)) hoverAnchorX = x;\n"
        "      if (y != null && Number.isFinite(y)) hoverAnchorY = y;\n"
        "      if (hoverAnchorX == null || hoverAnchorY == null) return;\n"
        "      var pad = 8;\n"
        "      var tw = tip.offsetWidth || 260;\n"
        "      var th = tip.offsetHeight || 120;\n"
        "      var vw = window.innerWidth || document.documentElement.clientWidth || 1024;\n"
        "      var vh = window.innerHeight || document.documentElement.clientHeight || 768;\n"
        "      var nx = hoverAnchorX + 14;\n"
        "      var ny = hoverAnchorY + 14;\n"
        "      if (nx + tw + pad > vw) nx = Math.max(pad, vw - tw - pad);\n"
        "      if (ny + th + pad > vh) ny = Math.max(pad, vh - th - pad);\n"
        "      tip.style.left = nx + \"px\";\n"
        "      tip.style.top = ny + \"px\";\n"
        "    }\n"
        "    function showHoverTip(lines, x, y) {\n"
        "      var tip = ensureHoverTip();\n"
        "      if (!tip) return;\n"
        "      clearHoverHideTimer();\n"
        "      tip.innerHTML = (lines || []).map(tooltipLineHtml).join(\"\");\n"
        "      tip.style.display = \"block\";\n"
        "      moveHoverTip(x, y);\n"
        "    }\n"
        "    function hideHoverTip(immediate) {\n"
        "      var tip = document.getElementById(\"cg-hover-tip\");\n"
        "      if (!tip) return;\n"
        "      clearHoverHideTimer();\n"
        "      if (!immediate && typeof window.setTimeout === \"function\") {\n"
        "        hoverHideTimer = window.setTimeout(function() {\n"
        "          tip.style.display = \"none\";\n"
        "          hoverAnchorX = null;\n"
        "          hoverAnchorY = null;\n"
        "          hoverHideTimer = 0;\n"
        "        }, 90);\n"
        "        return;\n"
        "      }\n"
        "      tip.style.display = \"none\";\n"
        "      hoverAnchorX = null;\n"
        "      hoverAnchorY = null;\n"
        "    }\n"
        "    function removeDefaultSidebarLegends() {\n"
        "      var sidebar = container.querySelector(\".sidebar_wrapper\");\n"
        "      if (!sidebar) return;\n"
        "      var opacitySlider = sidebar.querySelector(\".opacity_slider_container\");\n"
        "      if (opacitySlider) opacitySlider.style.display = \"none\";\n"
        "      var labels = sidebar.querySelectorAll(\".sidebar_text\");\n"
        "      for (var i = 0; i < labels.length; i++) {\n"
        "        var el = labels[i];\n"
        "        var text = (el.textContent || \"\").trim().toLowerCase();\n"
        "        if (text !== \"matrix values\") continue;\n"
        "        el.style.display = \"none\";\n"
        "        var next = el.nextElementSibling;\n"
        "        if (next && String(next.tagName || \"\").toLowerCase() === \"svg\") next.style.display = \"none\";\n"
        "      }\n"
        "    }\n"
        "    function colLabelNodes() {\n"
        "      var nodes = container.querySelectorAll(\".col_label_text text, text.col_label_text, .col_label_text\");\n"
        "      var out = [];\n"
        "      for (var i = 0; i < nodes.length; i++) {\n"
        "        var node = nodes[i];\n"
        "        if (!node || String(node.tagName || \"\").toLowerCase() !== \"text\") continue;\n"
        "        out.push(node);\n"
        "      }\n"
        "      return out;\n"
        "    }\n"
        "    function colLabelGroups() {\n"
        "      return Array.prototype.slice.call(container.querySelectorAll(\".col_label_text\"));\n"
        "    }\n"
        "    function rawColLabel(labelNode) {\n"
        "      if (!labelNode) return \"\";\n"
        "      return labelNode.getAttribute(\"full_name\") || ((labelNode.__data__ && labelNode.__data__.name) || \"\") || labelNode.textContent || \"\";\n"
        "    }\n"
        "    function displayLabelForPayload(label) {\n"
        "      return String(label == null ? \"\" : label).replace(/_/g, \" \");\n"
        "    }\n"
        "    function resolvePayloadColLabel(rawLabel) {\n"
        "      var target = String(rawLabel == null ? \"\" : rawLabel);\n"
        "      var payload = baseVizData();\n"
        "      var colNames = colNamesFromPayload(payload);\n"
        "      for (var i = 0; i < colNames.length; i++) {\n"
        "        if (displayLabelForPayload(colNames[i]) === target) return colNames[i];\n"
        "      }\n"
        "      return target;\n"
        "    }\n"
        "    function rawColGroupLabel(labelNode) {\n"
        "      if (!labelNode) return \"\";\n"
        "      var textNode = labelNode.querySelector ? labelNode.querySelector(\"text\") : null;\n"
        "      return rawColLabel(textNode || labelNode);\n"
        "    }\n"
        "    function rowLabelNodes() {\n"
        "      var nodes = container.querySelectorAll(\".row_label_group text, text.row_label_group\");\n"
        "      var out = [];\n"
        "      for (var i = 0; i < nodes.length; i++) {\n"
        "        var node = nodes[i];\n"
        "        if (!node || String(node.tagName || \"\").toLowerCase() !== \"text\") continue;\n"
        "        out.push(node);\n"
        "      }\n"
        "      return out;\n"
        "    }\n"
        "    function rowLabelGroups() {\n"
        "      return Array.prototype.slice.call(container.querySelectorAll(\".row_label_group\"));\n"
        "    }\n"
        "    function rawRowLabel(labelNode) {\n"
        "      if (!labelNode) return \"\";\n"
        "      return ((labelNode.__data__ && labelNode.__data__.name) || \"\") || labelNode.textContent || \"\";\n"
        "    }\n"
        "    function rawRowGroupLabel(labelNode) {\n"
        "      if (!labelNode) return \"\";\n"
        "      var textNode = labelNode.querySelector ? labelNode.querySelector(\"text\") : null;\n"
        "      return rawRowLabel(textNode || labelNode);\n"
        "    }\n"
        "    function syncShortColLabels() {\n"
        "      var labels = colLabelNodes();\n"
        "      for (var i = 0; i < labels.length; i++) {\n"
        "        var label = labels[i];\n"
        "        var meta = lookupColLabelMeta(rawColLabel(label));\n"
        "        var shortLabel = String(meta.pdb || \"\").trim() || String(label.textContent || \"\").trim();\n"
        "        shortLabel = shortLabel.replace(/\\.+$/, \"\");\n"
        "        if (!shortLabel) continue;\n"
        "        if (typeof label.removeAttribute === \"function\") {\n"
        "          label.removeAttribute(\"textLength\");\n"
        "          label.removeAttribute(\"lengthAdjust\");\n"
        "        }\n"
        "        label.style.letterSpacing = \"normal\";\n"
        "        if (label.textContent !== shortLabel) label.textContent = shortLabel;\n"
        "      }\n"
        "    }\n"
        "    function scheduleColLabelSync() {\n"
        "      if (colLabelFrame && typeof window.cancelAnimationFrame === \"function\") window.cancelAnimationFrame(colLabelFrame);\n"
        "      var run = function() {\n"
        "        colLabelFrame = 0;\n"
        "        syncShortColLabels();\n"
        "        attachColLabelHandlers();\n"
        "        attachRowLabelHandlers();\n"
        "        updateActiveLabelStates();\n"
        "      };\n"
        "      if (typeof window.requestAnimationFrame === \"function\") {\n"
        "        colLabelFrame = window.requestAnimationFrame(run);\n"
        "      } else {\n"
        "        run();\n"
        "      }\n"
        "    }\n"
        "    function bindColLabelObserver() {\n"
    )
