#!/usr/bin/env python3
"""Generate the repo map used for low-token orientation."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


DEFAULT_OUTPUT = Path("docs/repo_map/REPO_MAP.txt")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def repo_files(root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=root,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return sorted(line for line in result.stdout.splitlines() if line.strip())


def render_repo_map(paths: list[str]) -> str:
    lines = [
        "# Atlas2 Repo Map",
        "# Generated by: python tools/generate_repo_map.py",
        "# Contents: source files known to Git; runtime outputs and ignored local data are omitted.",
        "",
    ]
    lines.extend(paths)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    root = _repo_root()
    output = args.out if args.out.is_absolute() else root / args.out
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_repo_map(repo_files(root)), encoding="utf-8")
    print(output.relative_to(root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
